#include "src/codegen/rust/analysis_emitter.h"

#include "src/codegen/rust/code_writer.h"
#include "src/codegen/rust/shape_expression_emitter.h"

namespace tepl::codegen::rust {
namespace {
namespace shape = core::shape;

std::string operation(const DialectNames& dialect, const core::Operation& op) {
  return "Op::" + dialect.variant + "(" + dialect.module +
         "::Op::" + pascal(op.name) + ")";
}

void imports(CodeWriter& out, const Names& names, bool dtype) {
  out.line("// Generated by TEPL from checked operation definitions.");
  out.line(
      "#![allow(unused_imports, unused_variables, unused_parens, "
      "unreachable_code)]");
  for (const auto& dialect : names.dialects)
    out.line("use super::super::dialects::" + dialect.module + ";");
  out.line("use super::super::{Op, OpAttrs" +
           std::string(dtype ? ", DType" : "") + "};");
  out.line("use super::Inference;");
}

void signatureCheck(CodeWriter& out) {
  out.open(
      "if !op.arity().accepts(operands.len()) || !op.accepts_attrs(attrs)");
  out.line(
      "return Inference::Invalid(\"operand count or attributes do not match "
      "the operation signature\");");
  out.close();
}

// Only fields representable in shape expressions need conversion. The checker
// rejects optional and opaque fields when a shape program tries to read them.
std::string attributeValue(const core::AttributeField& field,
                           const std::string& value, std::size_t depth) {
  if (field.type == "bool") return value + ".clone()";
  if (!depth) return "i128::from(*" + value + ")";
  const auto item = "item_" + std::to_string(depth);
  return value + ".iter().map(|" + item + "| " +
         attributeValue(field, item, depth - 1) + ").collect::<Vec<_>>()";
}

void evaluator(CodeWriter& out, const core::Program& program,
               const Names& names, const DialectNames& dialect,
               const core::Operation& op) {
  const auto& checked = *op.shape;
  out.line("/// TEPL shape program for " + op.dialect + "." + op.name + ".");
  out.open("fn shape_" + std::to_string(op.id.value) +
           "(operands: &[&[u64]], attrs: &OpAttrs) -> "
           "super::super::builtins::BuiltinResult<Vec<u64>>");
  for (const auto& parameter : checked.parameters) {
    const auto value =
        parameter.variadic
            ? "operands[" + std::to_string(parameter.operand) +
                  "..].iter().map(|shape| "
                  "super::super::builtins::shape::integers(shape)).collect::<"
                  "Vec<_>>()"
            : "super::super::builtins::shape::integers(operands[" +
                  std::to_string(parameter.operand) + "])";
    out.line("let " + shapeSymbol(parameter.symbol) + ": " +
             shapeType(checked.types.at(
                 checked.symbols.at(parameter.symbol.value).type.value)) +
             " = " + value + ";");
  }
  if (op.attributes) {
    const auto& schema = program.attribute_schemas.at(op.attributes->value);
    std::string fields;
    for (std::size_t i = 0; i < schema.fields.size(); ++i) {
      const auto& field = schema.fields[i];
      if (field.optional || (field.type != "index" && field.type != "i64" &&
                             field.type != "bool"))
        continue;
      fields += identifier(field.name) + ": field_" + std::to_string(i) + ", ";
    }
    out.line("let OpAttrs::" + dialect.variant + "(" + dialect.module +
             "::OpAttrs::" + names.schema(*op.attributes) + " { " + fields +
             ".. }) = attrs else { return "
             "Err(super::super::builtins::BuiltinError::Assertion(\"invalid "
             "shape attributes\")); };");
    for (std::size_t i = 0; i < schema.fields.size(); ++i) {
      const auto& field = schema.fields[i];
      if (field.optional || (field.type != "index" && field.type != "i64" &&
                             field.type != "bool"))
        continue;
      const shape::Type type{field.type == "bool" ? shape::Type::Kind::kBoolean
                                                  : shape::Type::Kind::kInteger,
                             field.list_depth};
      out.line("let attribute_" + std::to_string(i) + ": " + shapeType(type) +
               " = " +
               attributeValue(field, "field_" + std::to_string(i),
                              field.list_depth) +
               ";");
    }
  }
  for (const auto& statement : checked.statements) {
    if (const auto* let = std::get_if<shape::Let>(&statement.value)) {
      out.line("let " + shapeSymbol(let->symbol) + ": " +
               shapeType(checked.types.at(let->value->type.value)) + " = " +
               shapeExpression(checked, *let->value) + ";");
    } else {
      const auto& assertion = std::get<shape::Assert>(statement.value);
      const auto& at = statement.origin.definition;
      out.line("super::super::builtins::common::ensure(" +
               shapeExpression(checked, *assertion.condition) + ", " +
               quote(op.dialect + "." + op.name + " shape assertion at " +
                     std::to_string(at.span.begin.line) + ":" +
                     std::to_string(at.span.begin.column)) +
               ")?;");
    }
  }
  out.line("super::super::builtins::shape::dimensions(&(" +
           shapeExpression(checked, *checked.result.value) + "))");
  out.close();
}
}  // namespace

std::string emitShapeInference(const core::Program& program,
                               const Names& names) {
  CodeWriter out;
  imports(out, names, false);
  out.open(
      "pub fn infer_shape(op: Op, operands: &[&[u64]], attrs: &OpAttrs) -> "
      "Inference<Vec<u64>>");
  signatureCheck(out);
  out.open(
      "let result: super::super::builtins::BuiltinResult<Vec<u64>> = match op");
  out.line("Op::Input => return Inference::Unknown,");
  out.line("Op::Literal => return Inference::Known(vec![]),");
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      out.line(operation(dialect, op) + " => " +
               (op.shape
                    ? "shape_" + std::to_string(id.value) + "(operands, attrs)"
                    : "return Inference::Unknown") +
               ",");
    }
  out.close(";");
  out.open("match result");
  out.line("Ok(shape) => Inference::Known(shape),");
  out.line("Err(error) => Inference::Invalid(error.message()),");
  out.close();
  out.close();
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      if (op.shape) evaluator(out, program, names, dialect, op);
    }
  return out.str();
}

std::string emitDTypeInference(const core::Program& program,
                               const Names& names) {
  CodeWriter out;
  imports(out, names, true);
  out.open(
      "pub fn infer_dtype(op: Op, operands: &[DType], attrs: &OpAttrs) -> "
      "Inference<DType>");
  signatureCheck(out);
  out.open("match op");
  out.line("Op::Input => Inference::Unknown,");
  out.line(
      "Op::Literal => { let OpAttrs::Literal { dtype, .. } = attrs else { "
      "unreachable!() }; "
      "dtype.map(Inference::Known).unwrap_or(Inference::Unknown) },");
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      std::string result = "Inference::Unknown";
      if (op.dtype_policy) {
        if (const auto* fixed = std::get_if<core::DType>(&*op.dtype_policy))
          result = "Inference::Known(" + dtype(*fixed) + ")";
        else
          result = "super::super::builtins::dtype::" +
                   std::string(core::dtypePolicyName(*op.dtype_policy)) +
                   "(operands)";
      }
      out.line(operation(dialect, op) + " => " + result + ",");
    }
  out.close();
  out.close();
  return out.str();
}
}  // namespace tepl::codegen::rust
