#include "src/codegen/rust/analysis_emitter.h"

#include "src/codegen/rust/code_writer.h"
#include "src/codegen/rust/metadata_expression_emitter.h"

namespace tepl::codegen::rust {
namespace {
namespace metadata = core::metadata;

std::string operation(const Names& names, const DialectNames& dialect,
                      const core::Operation& op) {
  return "Op::" + dialect.variant + "(" +
         names.operation(op.id, "super::super") + ")";
}

void imports(CodeWriter& out) {
  out.line("// Generated by TEPL from checked operation definitions.");
  out.line(
      "#![allow(unused_imports, unused_variables, unused_parens, "
      "unreachable_code)]");
  out.line("use super::super::{Op, OpAttrs, DType};");
  out.line("use super::Inference;");
}

void signatureCheck(CodeWriter& out) {
  out.open(
      "if !op.arity().accepts(operands.len()) || !op.accepts_attrs(attrs)");
  out.line(
      "return Inference::Invalid(\"operand count or attributes do not match "
      "the operation signature\");");
  out.close();
}

// Only fields representable in metadata expressions need conversion. The
// checker rejects optional and opaque fields when a program tries to read them.
std::string attributeValue(const core::AttributeField& field,
                           const std::string& value, std::size_t depth) {
  if (field.type == "bool" || field.type == "dtype") return value + ".clone()";
  if (!depth) return "i128::from(*" + value + ")";
  const auto item = "item_" + std::to_string(depth);
  return value + ".iter().map(|" + item + "| " +
         attributeValue(field, item, depth - 1) + ").collect::<Vec<_>>()";
}

void evaluator(CodeWriter& out, const core::Program& program,
               const Names& names, const DialectNames& dialect,
               const core::Operation& op, bool dtype_program = false) {
  const auto& checked = dtype_program ? *op.dtype : *op.shape;
  out.line("/// TEPL " + std::string(dtype_program ? "dtype" : "shape") +
           " program for " + op.dialect + "." + op.name + ".");
  out.open("fn " + std::string(dtype_program ? "dtype_" : "shape_") +
           std::to_string(op.id.value) +
           (dtype_program ? "(operands: &[DType], attrs: &OpAttrs) -> "
                            "super::super::builtins::BuiltinResult<DType>"
                          : "(operands: &[&[u64]], attrs: &OpAttrs) -> "
                            "super::super::builtins::BuiltinResult<Vec<u64>>"));
  for (const auto& parameter : checked.parameters) {
    const auto value =
        dtype_program
            ? (parameter.variadic
                   ? "operands[" + std::to_string(parameter.operand) +
                         "..].to_vec()"
                   : "operands[" + std::to_string(parameter.operand) + "]")
        : parameter.variadic
            ? "operands[" + std::to_string(parameter.operand) +
                  "..].iter().map(|shape| "
                  "super::super::builtins::shape::integers(shape)).collect::<"
                  "Vec<_>>()"
            : "super::super::builtins::shape::integers(operands[" +
                  std::to_string(parameter.operand) + "])";
    out.line("let " + metadataSymbol(parameter.symbol) + ": " +
             metadataType(checked.types.at(
                 checked.symbols.at(parameter.symbol.value).type.value)) +
             " = " + value + ";");
  }
  if (op.attributes) {
    const auto& schema = program.attribute_schemas.at(op.attributes->value);
    std::string fields;
    for (std::size_t i = 0; i < schema.fields.size(); ++i) {
      const auto& field = schema.fields[i];
      if (field.optional || (field.type != "index" && field.type != "i64" &&
                             field.type != "bool" && field.type != "dtype"))
        continue;
      fields +=
          names.field(schema.id, i) + ": field_" + std::to_string(i) + ", ";
    }
    out.line("let OpAttrs::" + dialect.variant +
             "(super::super::dialects::" + dialect.module +
             "::OpAttrs::" + names.schema(*op.attributes) + " { " + fields +
             ".. }) = attrs else { return "
             "Err(super::super::builtins::BuiltinError::Assertion(\"invalid "
             "metadata attributes\")); };");
    for (std::size_t i = 0; i < schema.fields.size(); ++i) {
      const auto& field = schema.fields[i];
      if (field.optional || (field.type != "index" && field.type != "i64" &&
                             field.type != "bool" && field.type != "dtype"))
        continue;
      const metadata::Type type{
          field.type == "bool"    ? metadata::Type::Kind::kBoolean
          : field.type == "dtype" ? metadata::Type::Kind::kDType
                                  : metadata::Type::Kind::kInteger,
          field.list_depth};
      out.line("let attribute_" + std::to_string(i) + ": " +
               metadataType(type) + " = " +
               attributeValue(field, "field_" + std::to_string(i),
                              field.list_depth) +
               ";");
    }
  }
  for (const auto& statement : checked.statements) {
    if (const auto* let = std::get_if<metadata::Let>(&statement.value)) {
      out.line("let " + metadataSymbol(let->symbol) + ": " +
               metadataType(checked.types.at(let->value->type.value)) + " = " +
               metadataExpression(checked, *let->value) + ";");
    } else {
      const auto& assertion = std::get<metadata::Assert>(statement.value);
      const auto& at = statement.origin.definition;
      out.line("super::super::builtins::common::ensure(" +
               metadataExpression(checked, *assertion.condition) + ", " +
               quote(op.dialect + "." + op.name +
                     (dtype_program ? " dtype assertion at "
                                    : " shape assertion at ") +
                     std::to_string(at.span.begin.line) + ":" +
                     std::to_string(at.span.begin.column)) +
               ")?;");
    }
  }
  if (dtype_program)
    out.line("Ok(" + metadataExpression(checked, *checked.result.value) + ")");
  else
    out.line("super::super::builtins::shape::dimensions(&(" +
             metadataExpression(checked, *checked.result.value) + "))");
  out.close();
}
}  // namespace

std::string emitShapeInference(const core::Program& program,
                               const Names& names) {
  CodeWriter out;
  imports(out);
  out.open(
      "pub fn infer_shape(op: Op, operands: &[&[u64]], attrs: &OpAttrs) -> "
      "Inference<Vec<u64>>");
  signatureCheck(out);
  out.open(
      "let result: super::super::builtins::BuiltinResult<Vec<u64>> = match op");
  out.line("Op::Input => return Inference::Unknown,");
  out.line("Op::Literal => return Inference::Known(vec![]),");
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      out.line(operation(names, dialect, op) + " => " +
               (op.shape
                    ? "shape_" + std::to_string(id.value) + "(operands, attrs)"
                    : "return Inference::Unknown") +
               ",");
    }
  out.close(";");
  out.open("match result");
  out.line("Ok(shape) => Inference::Known(shape),");
  out.line("Err(error) => Inference::Invalid(error.message()),");
  out.close();
  out.close();
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      if (op.shape) evaluator(out, program, names, dialect, op);
    }
  return out.str();
}

std::string emitDTypeInference(const core::Program& program,
                               const Names& names) {
  CodeWriter out;
  imports(out);
  out.open(
      "pub fn infer_dtype(op: Op, operands: &[DType], attrs: &OpAttrs) -> "
      "Inference<DType>");
  signatureCheck(out);
  out.open("match op");
  out.line("Op::Input => Inference::Unknown,");
  out.line(
      "Op::Literal => { let OpAttrs::Literal { dtype, .. } = attrs else { "
      "unreachable!() }; "
      "dtype.map(Inference::Known).unwrap_or(Inference::Unknown) },");
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      std::string result = "Inference::Unknown";
      if (op.dtype)
        result = "match dtype_" + std::to_string(op.id.value) +
                 "(operands, attrs) { Ok(dtype) => Inference::Known(dtype), "
                 "Err(error) => Inference::Invalid(error.message()) }";
      out.line(operation(names, dialect, op) + " => " + result + ",");
    }
  out.close();
  out.close();
  for (const auto& dialect : names.dialects)
    for (auto id : dialect.operations) {
      const auto& op = program.operations.at(id.value);
      if (op.dtype) evaluator(out, program, names, dialect, op, true);
    }
  return out.str();
}
}  // namespace tepl::codegen::rust
