#include "src/codegen/rust/dialect_emitter.h"

#include <map>

#include "src/codegen/rust/code_writer.h"

namespace tepl::codegen::rust {
std::string emitDialect(const core::Program& program, const Names& names,
                        const DialectNames& dialect) {
  CodeWriter out;
  out.line("// Generated by TEPL. Dialect: " + dialect.name);
  out.line("use super::super::op_node::{Arity, DialectOp, OpNode, NodeError};");
  out.line("use super::super::op_node::{Op as AnyOp, OpAttrs as AnyAttrs};");
  out.line(
      "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]");
  out.open("pub enum Op");
  for (auto id : dialect.operations) out.line(names.operationVariant(id) + ",");
  out.close();
  out.open("impl Op");
  out.open("pub fn name(self) -> &'static str");
  out.open("match self");
  for (auto id : dialect.operations) {
    const auto& op = program.operations[id.value];
    out.line("Self::" + names.operationVariant(op.id) + " => " +
             quote(op.name) + ",");
  }
  out.close();
  out.close();
  out.open("pub fn from_name(name: &str) -> Option<Self>");
  out.open("match name");
  for (auto id : dialect.operations) {
    const auto& op = program.operations[id.value];
    out.line(
        quote(op.name) +
        (op.alias && *op.alias != op.name ? " | " + quote(*op.alias) : "") +
        " => Some(Self::" + names.operationVariant(op.id) + "),");
  }
  out.line("_ => None,");
  out.close();
  out.close();
  out.open("pub fn arity(self) -> Arity");
  out.open("match self");
  for (auto id : dialect.operations) {
    const auto& op = program.operations[id.value];
    bool variadic = !op.operands.empty() && op.operands.back().variadic;
    out.line("Self::" + names.operationVariant(op.id) +
             " => Arity::" + (variadic ? "AtLeast(" : "Exact(") +
             std::to_string(op.operands.size() - (variadic ? 1 : 0)) + "),");
  }
  out.close();
  out.close();
  out.open("pub fn accepts_attrs(self, attrs: &OpAttrs) -> bool");
  out.open("match self");
  for (auto id : dialect.operations) {
    const auto& op = program.operations[id.value];
    out.line(
        "Self::" + names.operationVariant(op.id) +
        " => matches!(attrs, OpAttrs::" +
        (op.attributes ? names.schema(*op.attributes) + " { .. }" : "None") +
        "),");
  }
  out.close();
  out.close();
  out.close();
  out.line("#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]");
  out.open("pub enum OpAttrs");
  out.line("None,");
  for (auto id : dialect.schemas) {
    const auto& schema = program.attribute_schemas[id.value];
    out.open(names.schema(id));
    for (std::size_t i = 0; i < schema.fields.size(); ++i) {
      const auto& field = schema.fields[i];
      static const std::map<std::string, std::string> types = {
          {"index", "u64"},
          {"string", "String"},
          {"i64", "i64"},
          {"bool", "bool"},
          {"precision", "super::super::types::Precision"},
          {"dot_algorithm", "super::super::types::DotAlgorithm"},
          {"replica_groups", "super::super::types::ReplicaGroups"},
          {"region", "super::super::types::Region"},
          {"elements", "super::super::types::Elements"}};
      std::string type = types.at(field.type);
      for (std::size_t i = 0; i < field.list_depth; ++i)
        type = "Vec<" + type + ">";
      if (field.optional) type = "Option<" + type + ">";
      if (field.empty_default) out.line("// TEPL default: empty list.");
      out.line(names.field(id, i) + ": " + type + ",");
    }
    out.close(",");
  }
  out.close();
  out.open("impl OpAttrs");
  out.open("pub fn schema_id(&self) -> Option<usize>");
  out.open("match self");
  out.line("Self::None => None,");
  for (auto id : dialect.schemas)
    out.line("Self::" + names.schema(id) + " { .. } => Some(" +
             std::to_string(id.value) + "),");
  out.close();
  out.close();
  out.close();
  out.open("impl From<Op> for AnyOp");
  out.open("fn from(op: Op) -> Self");
  out.line("Self::" + dialect.variant + "(op)");
  out.close();
  out.close();
  out.open("impl From<OpAttrs> for AnyAttrs");
  out.open("fn from(attrs: OpAttrs) -> Self");
  out.line(dialect.schemas.empty()
               ? "match attrs { OpAttrs::None => Self::None }"
               : "match attrs { OpAttrs::None => Self::None, attrs => Self::" +
                     dialect.variant + "(attrs) }");
  out.close();
  out.close();
  out.open("impl DialectOp for Op");
  out.line("type Attrs = OpAttrs;");
  out.open(
      "fn into_node(self, attrs: OpAttrs, children: Vec<::egg::Id>) -> "
      "Result<OpNode, NodeError>");
  out.line("OpNode::from_parts(self.into(), children, attrs.into())");
  out.close();
  out.close();
  return out.str();
}
std::string emitOpUnion(const Names& names) {
  CodeWriter out;
  out.line(
      "// Generated sum types: one egg language, distinct dialect identities.");
  out.line(
      "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]");
  out.open("pub enum Op");
  out.line("Literal,");
  out.line("Input,");
  for (const auto& d : names.dialects)
    out.line(d.variant + "(super::dialects::" + d.module + "::Op),");
  out.close();
  out.line("#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]");
  out.open("pub enum OpAttrs");
  out.line("None,");
  out.line("Literal { value: String, dtype: Option<DType> },");
  out.line("Input { name: String },");
  for (const auto& d : names.dialects)
    out.line(d.variant + "(super::dialects::" + d.module + "::OpAttrs),");
  out.close();
  out.open("impl Op");
  out.open("pub fn name(self) -> &'static str");
  out.open("match self");
  out.line("Self::Literal => \"<literal>\",");
  out.line("Self::Input => \"<input>\",");
  for (const auto& d : names.dialects)
    out.line("Self::" + d.variant + "(op) => op.name(),");
  out.close();
  out.close();
  out.open("pub fn from_name(name: &str) -> Option<Self>");
  out.line("if name == \"<literal>\" { return Some(Self::Literal); }");
  out.line("if name == \"<input>\" { return Some(Self::Input); }");
  out.line("let (dialect, _op) = name.split_once('.')?;");
  out.open("match dialect");
  for (const auto& d : names.dialects)
    out.line(quote(d.name) + " => super::dialects::" + d.module +
             "::Op::from_name(_op).map(Self::" + d.variant + "),");
  out.line("_ => None,");
  out.close();
  out.close();
  out.open("pub fn arity(self) -> Arity");
  out.open("match self");
  out.line("Self::Literal | Self::Input => Arity::Exact(0),");
  for (const auto& d : names.dialects)
    out.line("Self::" + d.variant + "(op) => op.arity(),");
  out.close();
  out.close();
  out.open("pub fn accepts_attrs(self, attrs: &OpAttrs) -> bool");
  out.open("match (self, attrs)");
  out.line("(Self::Input, OpAttrs::Input { .. }) => true,");
  out.line(
      "(Self::Literal, OpAttrs::Literal { value, dtype }) => "
      "valid_literal(value) && dtype.is_none_or(|d| "
      "d.accepts_literal(value)),");
  for (const auto& d : names.dialects) {
    out.line("(Self::" + d.variant + "(op), OpAttrs::" + d.variant +
             "(attrs)) => op.accepts_attrs(attrs),");
    out.line("(Self::" + d.variant +
             "(op), OpAttrs::None) => op.accepts_attrs(&super::dialects::" +
             d.module + "::OpAttrs::None),");
  }
  out.line("_ => false,");
  out.close();
  out.close();
  out.close();
  out.open("impl OpAttrs");
  out.open("pub fn schema_id(&self) -> Option<usize>");
  out.open("match self");
  out.line("Self::None | Self::Literal { .. } | Self::Input { .. } => None,");
  for (const auto& d : names.dialects)
    out.line("Self::" + d.variant + "(attrs) => attrs.schema_id(),");
  out.close();
  out.close();
  out.open("pub fn checked_schema(self, schema: usize) -> Option<Self>");
  out.line("(self.schema_id() == Some(schema)).then_some(self)");
  out.close();
  out.close();
  return out.str();
}
}  // namespace tepl::codegen::rust
