#include "src/codegen/cpp/backend.h"

#include "src/codegen/cpp/analysis_emitter.h"
#include "src/codegen/cpp/dialect_emitter.h"
#include "src/codegen/cpp/graph_emitter.h"
#include "src/codegen/cpp/names.h"
#include "src/codegen/cpp/rule_emitter.h"
#include "src/codegen/cpp/template_files.h"

namespace tepl::codegen::cpp {
namespace {
void replace(std::string& text, const std::string& marker,
             const std::string& value) {
  std::size_t position = 0;
  while ((position = text.find(marker, position)) != std::string::npos) {
    text.replace(position, marker.size(), value);
    position += value.size();
  }
}
}  // namespace
GenerationResult Backend::generate(const core::Program& program,
                                   const Options& options) const {
  GenerationResult result;
  try {
    auto project =
        planProject(program, options.rules_root, options.graphs_root);
    Names names(program, project, options.cpp_namespace);
    std::string includes;
    for (const auto& d : names.dialects)
      includes += "#include \"dialects/" + d.file_stem + ".h\"\n";
    for (auto file : templateFiles()) {
      file.path.erase(0, 4);
      if (file.path == "op_node.h") {
        replace(file.contents, "// @tepl:dialect-includes", includes);
        replace(file.contents, "// @tepl:op-types",
                emitOpUnion(program, names));
      }
      replace(file.contents, "@TEPL_NAMESPACE@", options.cpp_namespace);
      result.files.push_back(std::move(file));
    }
    result.files.push_back(
        {"analysis/shape.h", emitShapeInference(program, names)});
    result.files.push_back(
        {"analysis/dtype.h", emitDTypeInference(program, names)});
    std::string dialect_index = "#pragma once\n";
    for (const auto& d : names.dialects) {
      result.files.push_back(
          {"dialects/" + d.file_stem + ".h", emitDialect(program, names, d)});
      dialect_index += "#include \"" + d.file_stem + ".h\"\n";
    }
    result.files.push_back({"dialects/dialects.h", dialect_index});
    for (const auto& [directory, children] : names.module_indexes) {
      std::string index = "#pragma once\n";
      for (const auto& child : children) {
        const auto path = directory.empty() ? child : directory + "/" + child;
        bool is_directory = names.module_indexes.contains(path);
        index +=
            "#include \"" + child + (is_directory ? "/rules.h" : ".h") + "\"\n";
      }
      result.files.push_back(
          {"rules/" + (directory.empty() ? "" : directory + "/") + "rules.h",
           index});
    }
    for (const auto& module : names.modules) {
      std::vector<const core::Rule*> rules;
      for (auto id : module.rules) rules.push_back(&program.rules.at(id.value));
      result.files.push_back({"rules/" + module.path + ".h",
                              emitRules(program, names, rules, module)});
    }
    emitGraphs(program, names, project, result);
    result.files.push_back(
        {"generated.h",
         "#pragma once\n#include \"op_node.h\"\n#include "
         "\"analysis/analysis.h\"\n#include \"builtins/builtins.h\"\n#include "
         "\"rewriting/rewrite.h\"\n#include \"rules/rules.h\"\n#include "
         "\"graphs/graphs.h\"\n"});
    // GCC can treat byte-identical #pragma once headers with matching
    // timestamps as the same file. Namespace-specific contents keep
    // wrapper/index headers distinct when multiple generated libraries share a
    // translation unit.
    for (auto& file : result.files)
      file.contents.insert(0, "// Generated by TEPL. C++ namespace: " +
                                  options.cpp_namespace + ".\n");
  } catch (const NameError& error) {
    result.files.clear();
    result.diagnostics.push_back({error.origin, error.what()});
  } catch (const std::invalid_argument& error) {
    result.files.clear();
    result.diagnostics.push_back({{}, error.what()});
  }
  return result;
}
}  // namespace tepl::codegen::cpp
