load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "format",
    srcs = ["tools/format.sh"],
)

cc_library(
    name = "source",
    hdrs = ["src/source.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "operators",
    hdrs = ["src/operators.h"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "format_check",
    srcs = ["tools/format.sh"],
    args = ["--check"],
)

cc_library(
    name = "frontend",
    srcs = ["src/parse.cc"],
    hdrs = ["src/parse.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//grammar:parser",
        "//src/ast:ast",
        "//src/ast:builder",
    ],
)

cc_library(
    name = "imports",
    srcs = ["src/imports.cc"],
    hdrs = ["src/imports.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":frontend",
        "//src/ast:ast",
    ],
)

cc_binary(
    name = "tepl",
    srcs = ["src/main.cc"],
    visibility = ["//tests:__pkg__"],
    deps = [
        ":frontend",
        ":imports",
        "//src/ast:ast",
        "//src/core:analysis",
        "//src/core:print",
        "@cli11//:cli11",
    ],
)
