load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "format",
    srcs = ["tools/format.sh"],
)

sh_binary(
    name = "format_check",
    srcs = ["tools/format.sh"],
    args = ["--check"],
)

cc_library(
    name = "frontend",
    srcs = ["src/parse.cc"],
    hdrs = ["src/parse.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//grammar:parser",
        "//src/ast:ast",
        "//src/ast:builder",
    ],
)

cc_library(
    name = "semantic",
    srcs = ["src/semantic.cc"],
    hdrs = ["src/semantic.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/ast:ast"],
)

cc_library(
    name = "host_codegen",
    srcs = ["src/host_codegen.cc"],
    hdrs = ["src/host_codegen.h"],
    visibility = ["//visibility:public"],
    deps = [":semantic", "//src/ast:ast"],
)

cc_library(
    name = "simple_rewrite",
    srcs = ["src/simple_rewrite.cc"],
    hdrs = ["src/simple_rewrite.h"],
    visibility = ["//visibility:public"],
    deps = [":semantic", "//src/ast:ast"],
)

cc_binary(
    name = "tepl",
    srcs = ["src/main.cc"],
    visibility = ["//tests:__pkg__"],
    deps = [
        ":frontend",
        ":host_codegen",
        ":semantic",
        "//src/ast:ast",
        "@cli11//:cli11",
    ],
)
