// Generated by TEPL. Dialect: DTypeExamples
use super::super::op_node::{Arity, DialectOp, NodeError, OpNode};
use super::super::op_node::{Op as AnyOp, OpAttrs as AnyAttrs};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Op {
    Equal,
    Convert,
    Select,
    ScalarZero,
}
impl Op {
    pub fn name(self) -> &'static str {
        match self {
            Self::Equal => "equal",
            Self::Convert => "convert",
            Self::Select => "select",
            Self::ScalarZero => "scalar_zero",
        }
    }
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "equal" => Some(Self::Equal),
            "convert" => Some(Self::Convert),
            "select" => Some(Self::Select),
            "scalar_zero" => Some(Self::ScalarZero),
            _ => None,
        }
    }
    pub fn arity(self) -> Arity {
        match self {
            Self::Equal => Arity::Exact(2),
            Self::Convert => Arity::Exact(1),
            Self::Select => Arity::Exact(3),
            Self::ScalarZero => Arity::Exact(0),
        }
    }
    pub fn accepts_attrs(self, attrs: &OpAttrs) -> bool {
        match self {
            Self::Equal => matches!(attrs, OpAttrs::None),
            Self::Convert => matches!(attrs, OpAttrs::ConvertAttrs { .. }),
            Self::Select => matches!(attrs, OpAttrs::None),
            Self::ScalarZero => matches!(attrs, OpAttrs::None),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OpAttrs {
    None,
    ConvertAttrs { to: super::super::DType },
}
impl OpAttrs {
    pub fn schema_id(&self) -> Option<usize> {
        match self {
            Self::None => None,
            Self::ConvertAttrs { .. } => Some(0),
        }
    }
}
impl From<Op> for AnyOp {
    fn from(op: Op) -> Self {
        Self::DTypeExamples(op)
    }
}
impl From<OpAttrs> for AnyAttrs {
    fn from(attrs: OpAttrs) -> Self {
        match attrs {
            OpAttrs::None => Self::None,
            attrs => Self::DTypeExamples(attrs),
        }
    }
}
impl DialectOp for Op {
    type Attrs = OpAttrs;
    fn into_node(self, attrs: OpAttrs, children: Vec<::egg::Id>) -> Result<OpNode, NodeError> {
        OpNode::from_parts(self.into(), children, attrs.into())
    }
}
