// Generated by TEPL. Dialect: Scalar
use super::super::op_node::{Arity, DialectOp, NodeError, OpNode};
use super::super::op_node::{Op as AnyOp, OpAttrs as AnyAttrs};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Op {
    Add,
    Negate,
}
impl Op {
    pub fn name(self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Negate => "negate",
        }
    }
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "add" => Some(Self::Add),
            "negate" => Some(Self::Negate),
            _ => None,
        }
    }
    pub fn arity(self) -> Arity {
        match self {
            Self::Add => Arity::Exact(2),
            Self::Negate => Arity::Exact(1),
        }
    }
    pub fn accepts_attrs(self, attrs: &OpAttrs) -> bool {
        match self {
            Self::Add => matches!(attrs, OpAttrs::None),
            Self::Negate => matches!(attrs, OpAttrs::None),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OpAttrs {
    None,
}
impl OpAttrs {
    pub fn schema_id(&self) -> Option<usize> {
        match self {
            Self::None => None,
        }
    }
}
impl From<Op> for AnyOp {
    fn from(op: Op) -> Self {
        Self::Scalar(op)
    }
}
impl From<OpAttrs> for AnyAttrs {
    fn from(attrs: OpAttrs) -> Self {
        match attrs {
            OpAttrs::None => Self::None,
        }
    }
}
impl DialectOp for Op {
    type Attrs = OpAttrs;
    fn into_node(self, attrs: OpAttrs, children: Vec<egg::Id>) -> Result<OpNode, NodeError> {
        OpNode::from_parts(self.into(), children, attrs.into())
    }
}
