// Generated by TEPL. Dialect: TensorLang
use super::super::op_node::{Arity, DialectOp, NodeError, OpNode};
use super::super::op_node::{Op as AnyOp, OpAttrs as AnyAttrs};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Op {
    Add,
    Subtract,
    Multiply,
    Divide,
    Maximum,
    Minimum,
    Negate,
    Exponential,
    Log,
    Abs,
    Sqrt,
    Rsqrt,
    Reshape,
    Transpose,
    BroadcastInDim,
    Slice,
    Concatenate,
    Reduce,
    DotGeneral,
    Convolution,
    AllGather,
    AllReduce,
    ReduceScatter,
    AllToAll,
    Constant,
}
impl Op {
    pub fn name(self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Subtract => "subtract",
            Self::Multiply => "multiply",
            Self::Divide => "divide",
            Self::Maximum => "maximum",
            Self::Minimum => "minimum",
            Self::Negate => "negate",
            Self::Exponential => "exponential",
            Self::Log => "log",
            Self::Abs => "abs",
            Self::Sqrt => "sqrt",
            Self::Rsqrt => "rsqrt",
            Self::Reshape => "reshape",
            Self::Transpose => "transpose",
            Self::BroadcastInDim => "broadcast_in_dim",
            Self::Slice => "slice",
            Self::Concatenate => "concatenate",
            Self::Reduce => "reduce",
            Self::DotGeneral => "dot_general",
            Self::Convolution => "convolution",
            Self::AllGather => "all_gather",
            Self::AllReduce => "all_reduce",
            Self::ReduceScatter => "reduce_scatter",
            Self::AllToAll => "all_to_all",
            Self::Constant => "constant",
        }
    }
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "add" => Some(Self::Add),
            "subtract" => Some(Self::Subtract),
            "multiply" | "mul" => Some(Self::Multiply),
            "divide" => Some(Self::Divide),
            "maximum" => Some(Self::Maximum),
            "minimum" => Some(Self::Minimum),
            "negate" => Some(Self::Negate),
            "exponential" | "exp" => Some(Self::Exponential),
            "log" => Some(Self::Log),
            "abs" => Some(Self::Abs),
            "sqrt" => Some(Self::Sqrt),
            "rsqrt" => Some(Self::Rsqrt),
            "reshape" => Some(Self::Reshape),
            "transpose" => Some(Self::Transpose),
            "broadcast_in_dim" => Some(Self::BroadcastInDim),
            "slice" => Some(Self::Slice),
            "concatenate" => Some(Self::Concatenate),
            "reduce" => Some(Self::Reduce),
            "dot_general" | "dot" => Some(Self::DotGeneral),
            "convolution" => Some(Self::Convolution),
            "all_gather" => Some(Self::AllGather),
            "all_reduce" => Some(Self::AllReduce),
            "reduce_scatter" => Some(Self::ReduceScatter),
            "all_to_all" => Some(Self::AllToAll),
            "constant" => Some(Self::Constant),
            _ => None,
        }
    }
    pub fn arity(self) -> Arity {
        match self {
            Self::Add => Arity::Exact(2),
            Self::Subtract => Arity::Exact(2),
            Self::Multiply => Arity::Exact(2),
            Self::Divide => Arity::Exact(2),
            Self::Maximum => Arity::Exact(2),
            Self::Minimum => Arity::Exact(2),
            Self::Negate => Arity::Exact(1),
            Self::Exponential => Arity::Exact(1),
            Self::Log => Arity::Exact(1),
            Self::Abs => Arity::Exact(1),
            Self::Sqrt => Arity::Exact(1),
            Self::Rsqrt => Arity::Exact(1),
            Self::Reshape => Arity::Exact(1),
            Self::Transpose => Arity::Exact(1),
            Self::BroadcastInDim => Arity::Exact(1),
            Self::Slice => Arity::Exact(1),
            Self::Concatenate => Arity::AtLeast(0),
            Self::Reduce => Arity::Exact(2),
            Self::DotGeneral => Arity::Exact(2),
            Self::Convolution => Arity::Exact(2),
            Self::AllGather => Arity::Exact(1),
            Self::AllReduce => Arity::Exact(1),
            Self::ReduceScatter => Arity::Exact(1),
            Self::AllToAll => Arity::Exact(1),
            Self::Constant => Arity::Exact(0),
        }
    }
    pub fn accepts_attrs(self, attrs: &OpAttrs) -> bool {
        match self {
            Self::Add => matches!(attrs, OpAttrs::None),
            Self::Subtract => matches!(attrs, OpAttrs::None),
            Self::Multiply => matches!(attrs, OpAttrs::None),
            Self::Divide => matches!(attrs, OpAttrs::None),
            Self::Maximum => matches!(attrs, OpAttrs::None),
            Self::Minimum => matches!(attrs, OpAttrs::None),
            Self::Negate => matches!(attrs, OpAttrs::None),
            Self::Exponential => matches!(attrs, OpAttrs::None),
            Self::Log => matches!(attrs, OpAttrs::None),
            Self::Abs => matches!(attrs, OpAttrs::None),
            Self::Sqrt => matches!(attrs, OpAttrs::None),
            Self::Rsqrt => matches!(attrs, OpAttrs::None),
            Self::Reshape => matches!(attrs, OpAttrs::ReshapeAttrs { .. }),
            Self::Transpose => matches!(attrs, OpAttrs::TransposeAttrs { .. }),
            Self::BroadcastInDim => matches!(attrs, OpAttrs::BroadcastInDimAttrs { .. }),
            Self::Slice => matches!(attrs, OpAttrs::SliceAttrs { .. }),
            Self::Concatenate => matches!(attrs, OpAttrs::ConcatenateAttrs { .. }),
            Self::Reduce => matches!(attrs, OpAttrs::ReduceAttrs { .. }),
            Self::DotGeneral => matches!(attrs, OpAttrs::DotGeneralAttrs { .. }),
            Self::Convolution => matches!(attrs, OpAttrs::ConvolutionAttrs { .. }),
            Self::AllGather => matches!(attrs, OpAttrs::AllGatherAttrs { .. }),
            Self::AllReduce => matches!(attrs, OpAttrs::CollectiveReduce { .. }),
            Self::ReduceScatter => matches!(attrs, OpAttrs::ReduceScatterAttrs { .. }),
            Self::AllToAll => matches!(attrs, OpAttrs::AllToAllAttrs { .. }),
            Self::Constant => matches!(attrs, OpAttrs::ConstantAttrs { .. }),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OpAttrs {
    None,
    CollectiveReduce {
        replica_groups: super::super::types::ReplicaGroups,
        channel_id: i64,
        use_global_device_ids: bool,
        computation: super::super::types::Region,
    },
    ReshapeAttrs {
        shape: Vec<u64>,
    },
    TransposeAttrs {
        permutation: Vec<u64>,
    },
    BroadcastInDimAttrs {
        broadcast_dimensions: Vec<u64>,
        shape: Vec<u64>,
    },
    SliceAttrs {
        start_indices: Vec<u64>,
        limit_indices: Vec<u64>,
        strides: Vec<u64>,
    },
    ConcatenateAttrs {
        dimension: u64,
    },
    ReduceAttrs {
        dimensions: Vec<u64>,
        body: super::super::types::Region,
    },
    DotGeneralAttrs {
        lhs_contracting_dimensions: Vec<u64>,
        rhs_contracting_dimensions: Vec<u64>,
        lhs_batching_dimensions: Vec<u64>,
        rhs_batching_dimensions: Vec<u64>,
        precision_config: Vec<super::super::types::Precision>,
        algorithm: Option<super::super::types::DotAlgorithm>,
    },
    ConvolutionAttrs {
        window_strides: Vec<u64>,
        padding: Vec<Vec<i64>>,
        lhs_dilation: Vec<u64>,
        rhs_dilation: Vec<u64>,
        window_reversal: Vec<bool>,
        input_batch_dimension: u64,
        input_feature_dimension: u64,
        input_spatial_dimensions: Vec<u64>,
        kernel_input_feature_dimension: u64,
        kernel_output_feature_dimension: u64,
        kernel_spatial_dimensions: Vec<u64>,
        output_batch_dimension: u64,
        output_feature_dimension: u64,
        output_spatial_dimensions: Vec<u64>,
        feature_group_count: u64,
        batch_group_count: u64,
        precision_config: Vec<super::super::types::Precision>,
    },
    AllGatherAttrs {
        all_gather_dim: u64,
        replica_groups: super::super::types::ReplicaGroups,
        channel_id: i64,
        use_global_device_ids: bool,
    },
    ReduceScatterAttrs {
        scatter_dimension: u64,
        replica_groups: super::super::types::ReplicaGroups,
        channel_id: i64,
        use_global_device_ids: bool,
        computation: super::super::types::Region,
    },
    AllToAllAttrs {
        split_dimension: u64,
        concat_dimension: u64,
        split_count: u64,
        replica_groups: super::super::types::ReplicaGroups,
        channel_id: i64,
    },
    ConstantAttrs {
        value: super::super::types::Elements,
    },
}
impl OpAttrs {
    pub fn schema_id(&self) -> Option<usize> {
        match self {
            Self::None => None,
            Self::CollectiveReduce { .. } => Some(0),
            Self::ReshapeAttrs { .. } => Some(1),
            Self::TransposeAttrs { .. } => Some(2),
            Self::BroadcastInDimAttrs { .. } => Some(3),
            Self::SliceAttrs { .. } => Some(4),
            Self::ConcatenateAttrs { .. } => Some(5),
            Self::ReduceAttrs { .. } => Some(6),
            Self::DotGeneralAttrs { .. } => Some(7),
            Self::ConvolutionAttrs { .. } => Some(8),
            Self::AllGatherAttrs { .. } => Some(9),
            Self::ReduceScatterAttrs { .. } => Some(10),
            Self::AllToAllAttrs { .. } => Some(11),
            Self::ConstantAttrs { .. } => Some(12),
        }
    }
}
impl From<Op> for AnyOp {
    fn from(op: Op) -> Self {
        Self::TensorLang(op)
    }
}
impl From<OpAttrs> for AnyAttrs {
    fn from(attrs: OpAttrs) -> Self {
        match attrs {
            OpAttrs::None => Self::None,
            attrs => Self::TensorLang(attrs),
        }
    }
}
impl DialectOp for Op {
    type Attrs = OpAttrs;
    fn into_node(self, attrs: OpAttrs, children: Vec<egg::Id>) -> Result<OpNode, NodeError> {
        OpNode::from_parts(self.into(), children, attrs.into())
    }
}
