// Generated by TEPL. Dialect: TensorLang
use super::super::op_node::{Arity, DialectOp, NodeError, OpNode};
use super::super::op_node::{Op as AnyOp, OpAttrs as AnyAttrs};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Op {
    Add,
    Subtract,
    Multiply,
    Divide,
    Maximum,
    Minimum,
    Negate,
    Exp,
    Log,
    Abs,
    Relu,
    Scale,
    Square,
    Sqrt,
    Rsqrt,
    Reshape,
    Transpose,
    Broadcast,
    Slice,
    Concatenate,
    Reduce,
    DotGeneral,
    Convolution,
    AllGather,
    AllReduce,
    ReduceScatter,
    AllToAll,
    Alias,
    Rmsnorm,
    VocabCrossEntropy,
    OnlineAttention,
    Constant,
    Symbol,
}
impl Op {
    pub fn name(self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Subtract => "subtract",
            Self::Multiply => "multiply",
            Self::Divide => "divide",
            Self::Maximum => "maximum",
            Self::Minimum => "minimum",
            Self::Negate => "negate",
            Self::Exp => "exp",
            Self::Log => "log",
            Self::Abs => "abs",
            Self::Relu => "relu",
            Self::Scale => "scale",
            Self::Square => "square",
            Self::Sqrt => "sqrt",
            Self::Rsqrt => "rsqrt",
            Self::Reshape => "reshape",
            Self::Transpose => "transpose",
            Self::Broadcast => "broadcast",
            Self::Slice => "slice",
            Self::Concatenate => "concatenate",
            Self::Reduce => "reduce",
            Self::DotGeneral => "dot_general",
            Self::Convolution => "convolution",
            Self::AllGather => "all_gather",
            Self::AllReduce => "all_reduce",
            Self::ReduceScatter => "reduce_scatter",
            Self::AllToAll => "all_to_all",
            Self::Alias => "alias",
            Self::Rmsnorm => "rmsnorm",
            Self::VocabCrossEntropy => "vocab_cross_entropy",
            Self::OnlineAttention => "online_attention",
            Self::Constant => "constant",
            Self::Symbol => "symbol",
        }
    }
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "add" => Some(Self::Add),
            "subtract" => Some(Self::Subtract),
            "multiply" | "mul" => Some(Self::Multiply),
            "divide" => Some(Self::Divide),
            "maximum" => Some(Self::Maximum),
            "minimum" => Some(Self::Minimum),
            "negate" => Some(Self::Negate),
            "exp" => Some(Self::Exp),
            "log" => Some(Self::Log),
            "abs" => Some(Self::Abs),
            "relu" => Some(Self::Relu),
            "scale" => Some(Self::Scale),
            "square" => Some(Self::Square),
            "sqrt" => Some(Self::Sqrt),
            "rsqrt" => Some(Self::Rsqrt),
            "reshape" => Some(Self::Reshape),
            "transpose" => Some(Self::Transpose),
            "broadcast" => Some(Self::Broadcast),
            "slice" => Some(Self::Slice),
            "concatenate" => Some(Self::Concatenate),
            "reduce" => Some(Self::Reduce),
            "dot_general" | "dot" => Some(Self::DotGeneral),
            "convolution" => Some(Self::Convolution),
            "all_gather" => Some(Self::AllGather),
            "all_reduce" => Some(Self::AllReduce),
            "reduce_scatter" => Some(Self::ReduceScatter),
            "all_to_all" => Some(Self::AllToAll),
            "alias" => Some(Self::Alias),
            "rmsnorm" => Some(Self::Rmsnorm),
            "vocab_cross_entropy" => Some(Self::VocabCrossEntropy),
            "online_attention" => Some(Self::OnlineAttention),
            "constant" => Some(Self::Constant),
            "symbol" => Some(Self::Symbol),
            _ => None,
        }
    }
    pub fn arity(self) -> Arity {
        match self {
            Self::Add => Arity::Exact(2),
            Self::Subtract => Arity::Exact(2),
            Self::Multiply => Arity::Exact(2),
            Self::Divide => Arity::Exact(2),
            Self::Maximum => Arity::Exact(2),
            Self::Minimum => Arity::Exact(2),
            Self::Negate => Arity::Exact(1),
            Self::Exp => Arity::Exact(1),
            Self::Log => Arity::Exact(1),
            Self::Abs => Arity::Exact(1),
            Self::Relu => Arity::Exact(1),
            Self::Scale => Arity::Exact(2),
            Self::Square => Arity::Exact(1),
            Self::Sqrt => Arity::Exact(1),
            Self::Rsqrt => Arity::Exact(1),
            Self::Reshape => Arity::Exact(1),
            Self::Transpose => Arity::Exact(1),
            Self::Broadcast => Arity::Exact(1),
            Self::Slice => Arity::Exact(1),
            Self::Concatenate => Arity::AtLeast(2),
            Self::Reduce => Arity::Exact(1),
            Self::DotGeneral => Arity::Exact(2),
            Self::Convolution => Arity::Exact(2),
            Self::AllGather => Arity::Exact(1),
            Self::AllReduce => Arity::Exact(1),
            Self::ReduceScatter => Arity::Exact(1),
            Self::AllToAll => Arity::Exact(1),
            Self::Alias => Arity::Exact(1),
            Self::Rmsnorm => Arity::Exact(1),
            Self::VocabCrossEntropy => Arity::Exact(2),
            Self::OnlineAttention => Arity::Exact(2),
            Self::Constant => Arity::Exact(0),
            Self::Symbol => Arity::Exact(0),
        }
    }
    pub fn accepts_attrs(self, attrs: &OpAttrs) -> bool {
        match self {
            Self::Add => matches!(attrs, OpAttrs::None),
            Self::Subtract => matches!(attrs, OpAttrs::None),
            Self::Multiply => matches!(attrs, OpAttrs::None),
            Self::Divide => matches!(attrs, OpAttrs::None),
            Self::Maximum => matches!(attrs, OpAttrs::None),
            Self::Minimum => matches!(attrs, OpAttrs::None),
            Self::Negate => matches!(attrs, OpAttrs::None),
            Self::Exp => matches!(attrs, OpAttrs::None),
            Self::Log => matches!(attrs, OpAttrs::None),
            Self::Abs => matches!(attrs, OpAttrs::None),
            Self::Relu => matches!(attrs, OpAttrs::None),
            Self::Scale => matches!(attrs, OpAttrs::None),
            Self::Square => matches!(attrs, OpAttrs::None),
            Self::Sqrt => matches!(attrs, OpAttrs::None),
            Self::Rsqrt => matches!(attrs, OpAttrs::None),
            Self::Reshape => matches!(attrs, OpAttrs::ReshapeAttrs { .. }),
            Self::Transpose => matches!(attrs, OpAttrs::TransposeAttrs { .. }),
            Self::Broadcast => matches!(attrs, OpAttrs::BroadcastAttrs { .. }),
            Self::Slice => matches!(attrs, OpAttrs::SliceAttrs { .. }),
            Self::Concatenate => matches!(attrs, OpAttrs::ConcatenateAttrs { .. }),
            Self::Reduce => matches!(attrs, OpAttrs::ReduceAttrs { .. }),
            Self::DotGeneral => matches!(attrs, OpAttrs::DotGeneralAttrs { .. }),
            Self::Convolution => matches!(attrs, OpAttrs::None),
            Self::AllGather => matches!(attrs, OpAttrs::None),
            Self::AllReduce => matches!(attrs, OpAttrs::CollectiveReduce { .. }),
            Self::ReduceScatter => matches!(attrs, OpAttrs::CollectiveReduce { .. }),
            Self::AllToAll => matches!(attrs, OpAttrs::None),
            Self::Alias => matches!(attrs, OpAttrs::None),
            Self::Rmsnorm => matches!(attrs, OpAttrs::None),
            Self::VocabCrossEntropy => matches!(attrs, OpAttrs::None),
            Self::OnlineAttention => matches!(attrs, OpAttrs::None),
            Self::Constant => matches!(attrs, OpAttrs::ConstantAttrs { .. }),
            Self::Symbol => matches!(attrs, OpAttrs::SymbolAttrs { .. }),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OpAttrs {
    None,
    CollectiveReduce {
        kind: String,
    },
    ReshapeAttrs {
        shape: Vec<u64>,
    },
    TransposeAttrs {
        permutation: Vec<u64>,
    },
    BroadcastAttrs {
        dimensions: Vec<u64>,
        shape: Vec<u64>,
    },
    SliceAttrs {
        start: Vec<u64>,
        limit: Vec<u64>,
        strides: Vec<u64>,
    },
    ConcatenateAttrs {
        axis: u64,
    },
    ReduceAttrs {
        kind: String,
        axes: Vec<u64>,
    },
    DotGeneralAttrs {
        lhs_contracting: Vec<u64>,
        rhs_contracting: Vec<u64>,
        lhs_batch: Vec<u64>,
        rhs_batch: Vec<u64>,
    },
    ConstantAttrs {
        name: String,
    },
    SymbolAttrs {
        name: String,
    },
}
impl OpAttrs {
    pub fn schema_id(&self) -> Option<usize> {
        match self {
            Self::None => None,
            Self::CollectiveReduce { .. } => Some(0),
            Self::ReshapeAttrs { .. } => Some(1),
            Self::TransposeAttrs { .. } => Some(2),
            Self::BroadcastAttrs { .. } => Some(3),
            Self::SliceAttrs { .. } => Some(4),
            Self::ConcatenateAttrs { .. } => Some(5),
            Self::ReduceAttrs { .. } => Some(6),
            Self::DotGeneralAttrs { .. } => Some(7),
            Self::ConstantAttrs { .. } => Some(8),
            Self::SymbolAttrs { .. } => Some(9),
        }
    }
}
impl From<Op> for AnyOp {
    fn from(op: Op) -> Self {
        Self::TensorLang(op)
    }
}
impl From<OpAttrs> for AnyAttrs {
    fn from(attrs: OpAttrs) -> Self {
        match attrs {
            OpAttrs::None => Self::None,
            attrs => Self::TensorLang(attrs),
        }
    }
}
impl DialectOp for Op {
    type Attrs = OpAttrs;
    fn into_node(self, attrs: OpAttrs, children: Vec<egg::Id>) -> Result<OpNode, NodeError> {
        OpNode::from_parts(self.into(), children, attrs.into())
    }
}
