load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "cli_test",
    size = "small",
    srcs = ["cli_test.sh"],
    args = [
        "$(rootpath //:tepl)",
        "$(rootpath //examples:simple.tepl)",
    ],
    data = [
        "//:tepl",
        "//examples:simple.tepl",
        "//examples:dialects/tensor.tepl",
        "//examples:abstract.tepl",
        "//examples:inherited.tepl",
        "//examples:basic.tepl",
    ],
)

cc_test(
    name = "ast_test",
    size = "small",
    srcs = ["ast_test.cc"],
    args = [
        "$(rlocationpath //examples:lora.tepl)",
        "$(rlocationpath //examples:dialects/tensor.tepl)",
        "$(rlocationpath //examples:abstract.tepl)",
        "$(rlocationpath //examples:inherited.tepl)",
    ],
    data = [
        "//examples:lora.tepl",
        "//examples:dialects/tensor.tepl",
        "//examples:abstract.tepl",
        "//examples:inherited.tepl",
    ],
    deps = [
        "//src/ast:ast",
        "//:frontend",
        "@rules_cc//cc/runfiles",
    ],
)

cc_test(
    name = "syntax_test",
    size = "small",
    srcs = ["syntax_test.cc"],
    deps = [
        "//:frontend",
        "//grammar:parser",
    ],
)

cc_test(
    name = "simple_rewrite_test",
    size = "small",
    srcs = ["simple_rewrite_test.cc"],
    deps = [
        "//:frontend",
        "//:semantic",
        "//:simple_rewrite",
    ],
)

cc_test(
    name = "host_codegen_test",
    size = "small",
    srcs = ["host_codegen_test.cc"],
    deps = [
        "//:frontend",
        "//:host_codegen",
    ],
)

cc_test(
    name = "dtype_test",
    size = "small",
    srcs = ["dtype_test.cc"],
    deps = [
        "//:frontend",
        "//:host_codegen",
        "//:semantic",
        "//:simple_rewrite",
        "//src/ast:ast",
    ],
)
