// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]
use super::super::analysis::{TensorAnalysis, infer_tensor_output, tensor_info};
use super::super::dialects::*;
use super::super::pattern::*;
use super::super::{DType, Op, OpAttrs, OpNode};
use egg::{Analysis, EGraph, Rewrite, Var};
use std::{collections::HashMap, sync::Arc};

pub mod rule_commute_f32 {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "basic::commute_f32",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let capture_1 = ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                if capture_0.dtype != DType::F32 {
                    return None;
                }
                dimensions.check(&capture_0.shape, &[ShapePart::Dimension(0)])?;
                if capture_1.dtype != DType::F32 {
                    return None;
                }
                dimensions.check(&capture_1.shape, &[ShapePart::Dimension(0)])?;
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_same_dtype {
    use super::*;
    pub trait Functions: Send + Sync {
        /// Host implementation of TEPL `$is_same_dtype(...)`.
        fn is_same_dtype(&self, arg0: &TensorInfo, arg1: &TensorInfo) -> Option<bool>;
    }
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "basic::commute_same_dtype",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let capture_1 = ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                dimensions.check(&capture_0.shape, &[ShapePart::Dimension(0)])?;
                dimensions.check(&capture_1.shape, &[ShapePart::Dimension(0)])?;
                if !(functions.is_same_dtype(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?),
                )?) {
                    return None;
                }
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_scalar {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "basic::commute_scalar",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let capture_1 = ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                if capture_0.dtype != DType::F32 {
                    return None;
                }
                dimensions.check(&capture_0.shape, &[])?;
                if capture_1.dtype != DType::F32 {
                    return None;
                }
                dimensions.check(&capture_1.shape, &[])?;
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_integer_literal {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::literal("1", Some(DType::I32)),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::literal("1", Some(DType::I32)),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "basic::commute_integer_literal",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                if capture_0.dtype != DType::I32 {
                    return None;
                }
                dimensions.check(&capture_0.shape, &[])?;
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_float_literal {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::literal("1.0", Some(DType::F32)),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::literal("1.0", Some(DType::F32)),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "basic::commute_float_literal",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                if capture_0.dtype != DType::F32 {
                    return None;
                }
                dimensions.check(&capture_0.shape, &[])?;
                Some(Default::default())
            },
        )
    }
}
