// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_commute_f32 {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![
            (
                "?c0".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: Some(DTypeConstraint::Exact(DType::F32)),
                    shape: vec![ShapePart::Dimension(0)],
                },
            ),
            (
                "?c1".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: Some(DTypeConstraint::Exact(DType::F32)),
                    shape: vec![ShapePart::Dimension(0)],
                },
            ),
        ])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "basic::commute_f32",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_same_dtype {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![
            (
                "?c0".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: Some(DTypeConstraint::Bind(0)),
                    shape: vec![ShapePart::Dimension(0)],
                },
            ),
            (
                "?c1".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: Some(DTypeConstraint::Bind(0)),
                    shape: vec![ShapePart::Dimension(0)],
                },
            ),
        ])
    }
    fn condition_0<N: RewriteAnalysis>(
        ctx: &MatchContext<'_, N, AnalysisMetadata<N>>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(super::super::super::builtins::dtype::is_numeric(
            dimensions.dtype(0)?,
        ))
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        let metadata = AnalysisMetadata::<N>::new();
        MatchChecks::new(
            constraints(),
            vec![vec![MatchBinding::DType(0)]],
            move |index, graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                match index {
                    0 => condition_0(&ctx, dimensions),
                    _ => None,
                }
            },
        )
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "basic::commute_same_dtype",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_scalar {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![
            (
                "?c0".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: Some(DTypeConstraint::Exact(DType::F32)),
                    shape: vec![],
                },
            ),
            (
                "?c1".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: Some(DTypeConstraint::Exact(DType::F32)),
                    shape: vec![],
                },
            ),
        ])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "basic::commute_scalar",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_integer_literal {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::literal("1", Some(DType::I32)),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::literal("1", Some(DType::I32)),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![(
            "?c0".parse::<Var>().expect("generated capture ID"),
            TensorConstraint {
                dtype: Some(DTypeConstraint::Exact(DType::I32)),
                shape: vec![],
            },
        )])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "basic::commute_integer_literal",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_float_literal {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::literal("1.0", Some(DType::F32)),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::literal("1.0", Some(DType::F32)),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![(
            "?c0".parse::<Var>().expect("generated capture ID"),
            TensorConstraint {
                dtype: Some(DTypeConstraint::Exact(DType::F32)),
                shape: vec![],
            },
        )])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "basic::commute_float_literal",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}
