// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]
use super::super::dialects::*;
use super::super::pattern::*;
use super::super::{DType, Op, OpAttrs, OpNode};
use egg::{Analysis, EGraph, Rewrite, Var};
use std::{collections::HashMap, sync::Arc};

pub mod rule_shared_expression {
    use super::*;
    pub trait Functions: Send + Sync {
        /// Host implementation of TEPL `$is_reusable(...)`.
        fn is_reusable(&self, arg0: &TensorInfo, arg1: &OpAttrs) -> Option<bool>;
    }
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::bind(
                    "?c2".parse::<Var>().expect("generated capture ID"),
                    TensorPattern::op(
                        tensor_lang::Op::DotGeneral,
                        AttrPattern::Bind(AttrVar::from("d0")),
                        vec![
                            TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                            TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        ],
                    ),
                ),
                TensorPattern::op(
                    tensor_lang::Op::Multiply,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c2".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::Var("?c3".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::op(
                    tensor_lang::Op::Multiply,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c3".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn build_rewrite<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "binders::shared_expression",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(7)?;
                let mut dimensions = ShapeBindings::default();
                if !(functions.is_reusable(
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(7)?),
                )?) {
                    return None;
                }
                Some(Default::default())
            },
        )
    }
}

pub mod rule_root_binding {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::bind(
            "?c1".parse::<Var>().expect("generated capture ID"),
            TensorPattern::op(
                tensor_lang::Op::Transpose,
                AttrPattern::Bind(AttrVar::from("d0")),
                vec![TensorPattern::Var(
                    "?c0".parse::<Var>().expect("generated capture ID"),
                )],
            ),
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID"))
    }
    pub fn build_rewrite<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "binders::root_binding",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(2)?;
                let mut dimensions = ShapeBindings::default();
                Some(Default::default())
            },
        )
    }
}
