// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_shared_expression {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {
        /// Host implementation of TEPL `$is_reusable(...)`.
        fn is_reusable(&self, arg0: &TensorInfo, arg1: &OpAttrs) -> Option<bool>;
    }
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::bind(
                    "?c2".parse::<Var>().expect("generated capture ID"),
                    TensorPattern::op(
                        super::super::super::dialects::tensor_lang::Op::DotGeneral,
                        AttrPattern::Bind(AttrVar::from("d0")),
                        vec![
                            TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                            TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        ],
                    ),
                ),
                TensorPattern::op(
                    super::super::super::dialects::tensor_lang::Op::Multiply,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c2".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::Var("?c3".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::op(
                    super::super::super::dialects::tensor_lang::Op::Multiply,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c3".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "binders::shared_expression",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(8)?;
                if !(functions.is_reusable(
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(8)?),
                )?) {
                    return None;
                }
                Some(Default::default())
            },
        )
    }
}

pub mod rule_root_binding {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::bind(
            "?c1".parse::<Var>().expect("generated capture ID"),
            TensorPattern::op(
                super::super::super::dialects::tensor_lang::Op::Transpose,
                AttrPattern::Bind(AttrVar::from("d0")),
                vec![TensorPattern::Var(
                    "?c0".parse::<Var>().expect("generated capture ID"),
                )],
            ),
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID"))
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "binders::root_binding",
            pattern(),
            expression(),
            checks,
            false,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(3)?;
                Some(Default::default())
            },
        )
    }
}
