// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]
use super::super::analysis::{TensorAnalysis, infer_tensor_output, tensor_info};
use super::super::dialects::*;
use super::super::pattern::*;
use super::super::{DType, Op, OpAttrs, OpNode};
use egg::{Analysis, EGraph, Rewrite, Var};
use std::{collections::HashMap, sync::Arc};

pub mod rule_cancel_negate_small {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Negate,
            AttrPattern::Exact(OpAttrs::None),
            vec![TensorPattern::op(
                tensor_lang::Op::Negate,
                AttrPattern::Exact(OpAttrs::None),
                vec![TensorPattern::Var(
                    "?c0".parse::<Var>().expect("generated capture ID"),
                )],
            )],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID"))
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![(
            "?c0".parse::<Var>().expect("generated capture ID"),
            TensorConstraint {
                dtype: None,
                shape: vec![ShapePart::Sequence(Some(0))],
            },
        )])
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked_with_constraints(
            "builtins::cancel_negate_small",
            pattern(),
            expression(),
            constraints(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                if !((super::super::super::builtins::common::index_len(
                    &(dimensions.sequence(0)?.to_vec()),
                )
                .ok()?)
                    <= ("4".parse::<u64>().ok()?))
                {
                    return None;
                }
                if !((super::super::super::builtins::common::product(
                    &(dimensions.sequence(0)?.to_vec()),
                )
                .ok()?)
                    <= ("4096".parse::<u64>().ok()?))
                {
                    return None;
                }
                Some(Default::default())
            },
        )
    }
}
