// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_cancel_negate_small {
    use super::super::super::analysis::{TensorAnalysis, infer_tensor_output, tensor_info};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, MatchBinding, MatchChecks, MatchContext, MetadataBindings,
        OutputInference, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorMetadata, TensorPattern, tensor_rewrite_checked_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{Analysis, EGraph, Rewrite, Var};
    use ::std::{collections::HashMap, sync::Arc};
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Negate,
            AttrPattern::Exact(OpAttrs::None),
            vec![TensorPattern::op(
                super::super::super::dialects::tensor_lang::Op::Negate,
                AttrPattern::Exact(OpAttrs::None),
                vec![TensorPattern::Var(
                    "?c0".parse::<Var>().expect("generated capture ID"),
                )],
            )],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID"))
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![(
            "?c0".parse::<Var>().expect("generated capture ID"),
            TensorConstraint {
                dtype: None,
                shape: vec![ShapePart::Sequence(Some(0))],
            },
        )])
    }
    fn condition_0<N: Analysis<OpNode>, M: TensorMetadata<N>>(
        ctx: &MatchContext<'_, N, M>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(
            ((super::super::super::builtins::common::index_len(
                &(dimensions.sequence(0)?.to_vec()),
            )
            .ok()?)
                <= ("4".parse::<u64>().ok()?)),
        )
    }
    fn condition_1<N: Analysis<OpNode>, M: TensorMetadata<N>>(
        ctx: &MatchContext<'_, N, M>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(
            ((super::super::super::builtins::common::product(&(dimensions.sequence(0)?.to_vec()))
                .ok()?)
                <= ("4096".parse::<u64>().ok()?)),
        )
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: Analysis<OpNode>, M: TensorMetadata<N> + 'static>(
        metadata: Arc<M>,
    ) -> MatchChecks<N> {
        MatchChecks::new(
            constraints(),
            vec![
                vec![MatchBinding::Sequence(0)],
                vec![MatchBinding::Sequence(0)],
            ],
            move |index, graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, metadata.as_ref());
                match index {
                    0 => condition_0(&ctx, dimensions),
                    1 => condition_1(&ctx, dimensions),
                    _ => None,
                }
            },
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode> + 'static,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checks = match_checks::<N, M>(metadata.clone());
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked_with_checks(
            "builtins::cancel_negate_small",
            pattern(),
            expression(),
            checks,
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                Some(Default::default())
            },
        )
    }
}
