// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_cancel_negate_small {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Negate,
            AttrPattern::Exact(OpAttrs::None),
            vec![TensorPattern::op(
                super::super::super::dialects::tensor_lang::Op::Negate,
                AttrPattern::Exact(OpAttrs::None),
                vec![TensorPattern::Var(
                    "?c0".parse::<Var>().expect("generated capture ID"),
                )],
            )],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID"))
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![(
            "?c0".parse::<Var>().expect("generated capture ID"),
            TensorConstraint {
                dtype: None,
                shape: vec![ShapePart::Sequence(Some(0))],
            },
        )])
    }
    fn condition_0<N: RewriteAnalysis>(
        ctx: &MatchContext<'_, N, AnalysisMetadata<N>>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(
            ((super::super::super::builtins::common::index_len(
                &(dimensions.sequence(0)?.to_vec()),
            )
            .ok()?)
                <= ("4".parse::<u64>().ok()?)),
        )
    }
    fn condition_1<N: RewriteAnalysis>(
        ctx: &MatchContext<'_, N, AnalysisMetadata<N>>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(
            ((super::super::super::builtins::common::product(&(dimensions.sequence(0)?.to_vec()))
                .ok()?)
                <= ("4096".parse::<u64>().ok()?)),
        )
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        let metadata = AnalysisMetadata::<N>::new();
        MatchChecks::new(
            constraints(),
            vec![
                vec![MatchBinding::Sequence(0)],
                vec![MatchBinding::Sequence(0)],
            ],
            move |index, graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                match index {
                    0 => condition_0(&ctx, dimensions),
                    1 => condition_1(&ctx, dimensions),
                    _ => None,
                }
            },
        )
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "builtins::cancel_negate_small",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}
