// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_remove_identity_convert {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::d_type_examples::Op::Convert,
            AttrPattern::Bind(AttrVar::from("d0")),
            vec![TensorPattern::Var(
                "?c0".parse::<Var>().expect("generated capture ID"),
            )],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID"))
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![(
            "?c0".parse::<Var>().expect("generated capture ID"),
            TensorConstraint {
                dtype: Some(DTypeConstraint::Bind(0)),
                shape: vec![ShapePart::Sequence(None)],
            },
        )])
    }
    fn condition_0<N: RewriteAnalysis>(
        ctx: &MatchContext<'_, N, AnalysisMetadata<N>>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(super::super::super::builtins::dtype::is_numeric(
            dimensions.dtype(0)?,
        ))
    }
    fn condition_1<N: RewriteAnalysis>(
        ctx: &MatchContext<'_, N, AnalysisMetadata<N>>,
        dimensions: &MetadataBindings,
    ) -> Option<bool> {
        Some(
            (((match ctx.attrs(AttrVar::from("d0"))? {
                OpAttrs::DTypeExamples(
                    super::super::super::dialects::d_type_examples::OpAttrs::ConvertAttrs {
                        to: field,
                        ..
                    },
                ) => Some(field.clone()),
                _ => None,
            })?) == (dimensions.dtype(0)?)),
        )
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        let metadata = AnalysisMetadata::<N>::new();
        MatchChecks::new(
            constraints(),
            vec![
                vec![MatchBinding::DType(0)],
                vec![
                    MatchBinding::Attribute(AttrVar::from("d0")),
                    MatchBinding::DType(0),
                ],
            ],
            move |index, graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                match index {
                    0 => condition_0(&ctx, dimensions),
                    1 => condition_1(&ctx, dimensions),
                    _ => None,
                }
            },
        )
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "dtype::remove_identity_convert",
            pattern(),
            expression(),
            checks,
            true,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(0)?;
                Some(Default::default())
            },
        )
    }
}
