// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]
use super::super::analysis::{TensorAnalysis, infer_tensor_output, tensor_info};
use super::super::dialects::*;
use super::super::pattern::*;
use super::super::{DType, Op, OpAttrs, OpNode};
use egg::{Analysis, EGraph, Rewrite, Var};
use std::{collections::HashMap, sync::Arc};

pub mod rule_commute_add {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::commute_add",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let mut dimensions = ShapeBindings::default();
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_mul {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Multiply,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Multiply,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::commute_mul",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let mut dimensions = ShapeBindings::default();
                Some(Default::default())
            },
        )
    }
}

pub mod rule_commute_small_vectors {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::commute_small_vectors",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let capture_1 = ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                dimensions.check(&capture_0.shape, &[ShapePart::Dimension(0)])?;
                dimensions.check(&capture_1.shape, &[ShapePart::Dimension(0)])?;
                if !((dimensions.dimension(0)?) <= ("1024".parse::<u64>().ok()?)) {
                    return None;
                }
                Some(Default::default())
            },
        )
    }
}

pub mod rule_associate_add_right {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::op(
                    tensor_lang::Op::Add,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorPattern::Var("?c2".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorExpr::op(
                    tensor_lang::Op::Add,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::associate_add_right",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let mut dimensions = ShapeBindings::default();
                Some(Default::default())
            },
        )
    }
}

pub mod rule_associate_mul_right {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Multiply,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::op(
                    tensor_lang::Op::Multiply,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorPattern::Var("?c2".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Multiply,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorExpr::op(
                    tensor_lang::Op::Multiply,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::associate_mul_right",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let mut dimensions = ShapeBindings::default();
                Some(Default::default())
            },
        )
    }
}

pub mod rule_associate_small_vectors {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::op(
                    tensor_lang::Op::Add,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorPattern::Var("?c2".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorExpr::op(
                    tensor_lang::Op::Add,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::associate_small_vectors",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let capture_1 = ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?;
                let capture_2 = ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?;
                let mut dimensions = ShapeBindings::default();
                dimensions.check(&capture_0.shape, &[ShapePart::Dimension(0)])?;
                dimensions.check(&capture_1.shape, &[ShapePart::Dimension(0)])?;
                dimensions.check(&capture_2.shape, &[ShapePart::Dimension(0)])?;
                if !((dimensions.dimension(0)?) <= ("1024".parse::<u64>().ok()?)) {
                    return None;
                }
                Some(Default::default())
            },
        )
    }
}

pub mod rule_distribute_mul_over_add {
    use super::*;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::Multiply,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::op(
                    tensor_lang::Op::Add,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::Var("?c2".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::op(
                    tensor_lang::Op::Multiply,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorExpr::op(
                    tensor_lang::Op::Multiply,
                    AttrExpr::Exact(OpAttrs::None),
                    vec![
                        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c2".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "inherited::distribute_mul_over_add",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let mut dimensions = ShapeBindings::default();
                Some(Default::default())
            },
        )
    }
}
