// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]
use super::super::dialects::*;
use super::super::pattern::*;
use super::super::{DType, Op, OpAttrs, OpNode};
use egg::{Analysis, EGraph, Rewrite, Var};
use std::{collections::HashMap, sync::Arc};

pub mod rule_lora {
    use super::*;
    pub trait Functions: Send + Sync {
        fn broadcastable(&self, arg0: &[u64], arg1: &[u64]) -> Option<bool>;
        fn reassociable(
            &self,
            arg0: &TensorInfo,
            arg1: &TensorInfo,
            arg2: &TensorInfo,
            arg3: &OpAttrs,
            arg4: &OpAttrs,
        ) -> Option<bool>;
        fn infer_dot(
            &self,
            arg0: &TensorInfo,
            arg1: &TensorInfo,
            arg2: &OpAttrs,
        ) -> Option<OpAttrs>;
        fn infer_lora_out(
            &self,
            arg0: &TensorInfo,
            arg1: &TensorInfo,
            arg2: &TensorInfo,
            arg3: &OpAttrs,
            arg4: &OpAttrs,
        ) -> Option<OpAttrs>;
    }
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            tensor_lang::Op::DotGeneral,
            AttrPattern::Bind(AttrVar::from("d0")),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::op(
                    tensor_lang::Op::Add,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::op(
                            tensor_lang::Op::DotGeneral,
                            AttrPattern::Bind(AttrVar::from("d1")),
                            vec![
                                TensorPattern::Var(
                                    "?c2".parse::<Var>().expect("generated capture ID"),
                                ),
                                TensorPattern::Var(
                                    "?c3".parse::<Var>().expect("generated capture ID"),
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::op(
                    tensor_lang::Op::DotGeneral,
                    AttrExpr::Derived(AttrVar::from("d2")),
                    vec![
                        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorExpr::op(
                    tensor_lang::Op::DotGeneral,
                    AttrExpr::Derived(AttrVar::from("d4")),
                    vec![
                        TensorExpr::op(
                            tensor_lang::Op::DotGeneral,
                            AttrExpr::Derived(AttrVar::from("d3")),
                            vec![
                                TensorExpr::Var(
                                    "?c0".parse::<Var>().expect("generated capture ID"),
                                ),
                                TensorExpr::Var(
                                    "?c2".parse::<Var>().expect("generated capture ID"),
                                ),
                            ],
                        ),
                        TensorExpr::Var("?c3".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    pub fn build_rewrite<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode>,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked(
            "lora::lora",
            pattern(),
            expression(),
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let capture_0 = ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?;
                let capture_1 = ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?;
                let capture_2 = ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?;
                let capture_3 = ctx.tensor("?c3".parse::<Var>().expect("generated capture ID"))?;
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(7)?;
                let descriptor_1 = ctx.attrs(AttrVar::from("d1"))?.clone();
                let descriptor_1 = descriptor_1.checked_schema(7)?;
                let mut dimensions = ShapeBindings::default();
                dimensions.check(
                    &capture_0.shape,
                    &[
                        ShapePart::Sequence(Some(0)),
                        ShapePart::Dimension(1),
                        ShapePart::Dimension(2),
                    ],
                )?;
                dimensions.check(
                    &capture_1.shape,
                    &[
                        ShapePart::Sequence(Some(3)),
                        ShapePart::Dimension(2),
                        ShapePart::Dimension(4),
                    ],
                )?;
                dimensions.check(
                    &capture_2.shape,
                    &[
                        ShapePart::Sequence(Some(3)),
                        ShapePart::Dimension(2),
                        ShapePart::Dimension(5),
                    ],
                )?;
                dimensions.check(
                    &capture_3.shape,
                    &[
                        ShapePart::Sequence(Some(3)),
                        ShapePart::Dimension(5),
                        ShapePart::Dimension(4),
                    ],
                )?;
                if !(functions.broadcastable(
                    &(dimensions.sequence(0)?.to_vec()),
                    &(dimensions.sequence(3)?.to_vec()),
                )?) {
                    return None;
                }
                if !(functions.reassociable(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c3".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(7)?),
                    &((descriptor_1.clone()).checked_schema(7)?),
                )?) {
                    return None;
                }
                let descriptor_2 = (functions.infer_dot(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(7)?),
                )?)
                .checked_schema(7)?;
                let descriptor_3 = (functions.infer_dot(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(7)?),
                )?)
                .checked_schema(7)?;
                let descriptor_4 = (functions.infer_lora_out(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c3".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(7)?),
                    &((descriptor_1.clone()).checked_schema(7)?),
                )?)
                .checked_schema(7)?;
                Some(HashMap::from([
                    (AttrVar::from("d2"), descriptor_2),
                    (AttrVar::from("d3"), descriptor_3),
                    (AttrVar::from("d4"), descriptor_4),
                ]))
            },
        )
    }
}
