// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_lora {
    use super::super::super::analysis::{TensorAnalysis, infer_tensor_output, tensor_info};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, MatchBinding, MatchChecks, MatchContext, MetadataBindings,
        OutputInference, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorMetadata, TensorPattern, tensor_rewrite_checked_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{Analysis, EGraph, Rewrite, Var};
    use ::std::{collections::HashMap, sync::Arc};
    pub trait Functions: Send + Sync {
        /// Host implementation of TEPL `$is_broadcastable(...)`.
        fn is_broadcastable(&self, arg0: &[u64], arg1: &[u64]) -> Option<bool>;
        /// Host implementation of TEPL `$is_reassociable(...)`.
        fn is_reassociable(
            &self,
            arg0: &TensorInfo,
            arg1: &TensorInfo,
            arg2: &TensorInfo,
            arg3: &OpAttrs,
            arg4: &OpAttrs,
        ) -> Option<bool>;
        /// Host implementation of TEPL `$infer_dot(...)`.
        fn infer_dot(
            &self,
            arg0: &TensorInfo,
            arg1: &TensorInfo,
            arg2: &OpAttrs,
        ) -> Option<OpAttrs>;
        /// Host implementation of TEPL `$infer_lora_out(...)`.
        fn infer_lora_out(
            &self,
            arg0: &TensorInfo,
            arg1: &TensorInfo,
            arg2: &TensorInfo,
            arg3: &OpAttrs,
            arg4: &OpAttrs,
        ) -> Option<OpAttrs>;
    }
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::DotGeneral,
            AttrPattern::Bind(AttrVar::from("d0")),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::op(
                    super::super::super::dialects::tensor_lang::Op::Add,
                    AttrPattern::Exact(OpAttrs::None),
                    vec![
                        TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
                        TensorPattern::op(
                            super::super::super::dialects::tensor_lang::Op::DotGeneral,
                            AttrPattern::Bind(AttrVar::from("d1")),
                            vec![
                                TensorPattern::Var(
                                    "?c2".parse::<Var>().expect("generated capture ID"),
                                ),
                                TensorPattern::Var(
                                    "?c3".parse::<Var>().expect("generated capture ID"),
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::op(
                    super::super::super::dialects::tensor_lang::Op::DotGeneral,
                    AttrExpr::Derived(AttrVar::from("d2")),
                    vec![
                        TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
                        TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
                TensorExpr::op(
                    super::super::super::dialects::tensor_lang::Op::DotGeneral,
                    AttrExpr::Derived(AttrVar::from("d4")),
                    vec![
                        TensorExpr::op(
                            super::super::super::dialects::tensor_lang::Op::DotGeneral,
                            AttrExpr::Derived(AttrVar::from("d3")),
                            vec![
                                TensorExpr::Var(
                                    "?c0".parse::<Var>().expect("generated capture ID"),
                                ),
                                TensorExpr::Var(
                                    "?c2".parse::<Var>().expect("generated capture ID"),
                                ),
                            ],
                        ),
                        TensorExpr::Var("?c3".parse::<Var>().expect("generated capture ID")),
                    ],
                ),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![
            (
                "?c0".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: None,
                    shape: vec![
                        ShapePart::Sequence(Some(0)),
                        ShapePart::Dimension(1),
                        ShapePart::Dimension(2),
                    ],
                },
            ),
            (
                "?c1".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: None,
                    shape: vec![
                        ShapePart::Sequence(Some(3)),
                        ShapePart::Dimension(2),
                        ShapePart::Dimension(4),
                    ],
                },
            ),
            (
                "?c2".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: None,
                    shape: vec![
                        ShapePart::Sequence(Some(3)),
                        ShapePart::Dimension(2),
                        ShapePart::Dimension(5),
                    ],
                },
            ),
            (
                "?c3".parse::<Var>().expect("generated capture ID"),
                TensorConstraint {
                    dtype: None,
                    shape: vec![
                        ShapePart::Sequence(Some(3)),
                        ShapePart::Dimension(5),
                        ShapePart::Dimension(4),
                    ],
                },
            ),
        ])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: Analysis<OpNode>, M: TensorMetadata<N> + 'static>(
        metadata: Arc<M>,
    ) -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode> + 'static,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checks = match_checks::<N, M>(metadata.clone());
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked_with_checks(
            "lora::lora",
            pattern(),
            expression(),
            checks,
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                let descriptor_0 = ctx.attrs(AttrVar::from("d0"))?.clone();
                let descriptor_0 = descriptor_0.checked_schema(8)?;
                let descriptor_1 = ctx.attrs(AttrVar::from("d1"))?.clone();
                let descriptor_1 = descriptor_1.checked_schema(8)?;
                if !(functions.is_broadcastable(
                    &(dimensions.sequence(0)?.to_vec()),
                    &(dimensions.sequence(3)?.to_vec()),
                )?) {
                    return None;
                }
                if !(functions.is_reassociable(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c3".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(8)?),
                    &((descriptor_1.clone()).checked_schema(8)?),
                )?) {
                    return None;
                }
                let descriptor_2 = (functions.infer_dot(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c1".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(8)?),
                )?)
                .checked_schema(8)?;
                let descriptor_3 = (functions.infer_dot(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(8)?),
                )?)
                .checked_schema(8)?;
                let descriptor_4 = (functions.infer_lora_out(
                    &(ctx.tensor("?c0".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c2".parse::<Var>().expect("generated capture ID"))?),
                    &(ctx.tensor("?c3".parse::<Var>().expect("generated capture ID"))?),
                    &((descriptor_0.clone()).checked_schema(8)?),
                    &((descriptor_1.clone()).checked_schema(8)?),
                )?)
                .checked_schema(8)?;
                Some(HashMap::from([
                    (AttrVar::from("d2"), descriptor_2),
                    (AttrVar::from("d3"), descriptor_3),
                    (AttrVar::from("d4"), descriptor_4),
                ]))
            },
        )
    }
}
