// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_commute_add {
    use super::super::super::analysis::{TensorAnalysis, infer_tensor_output, tensor_info};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, MatchBinding, MatchChecks, MatchContext, MetadataBindings,
        OutputInference, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorMetadata, TensorPattern, tensor_rewrite_checked_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{Analysis, EGraph, Rewrite, Var};
    use ::std::{collections::HashMap, sync::Arc};
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::scalar::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::scalar::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: Analysis<OpNode>, M: TensorMetadata<N> + 'static>(
        metadata: Arc<M>,
    ) -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the same metadata and inference as TensorAnalysis.
    pub fn build_rewrite<F: Functions + 'static>(
        functions: F,
    ) -> Result<Rewrite<OpNode, TensorAnalysis>, String> {
        build_rewrite_with(tensor_info, infer_tensor_output, functions)
    }
    /// Explicit hooks for a custom analysis or inference policy.
    pub fn build_rewrite_with<N, M, I, F>(
        metadata: M,
        inference: I,
        functions: F,
    ) -> Result<Rewrite<OpNode, N>, String>
    where
        N: Analysis<OpNode> + 'static,
        M: TensorMetadata<N> + 'static,
        I: OutputInference + 'static,
        F: Functions + 'static,
    {
        let metadata = Arc::new(metadata);
        let checks = match_checks::<N, M>(metadata.clone());
        let checker_metadata = metadata.clone();
        tensor_rewrite_checked_with_checks(
            "scalar::commute_add",
            pattern(),
            expression(),
            checks,
            move |graph: &EGraph<OpNode, N>, id| metadata.info(graph, id),
            inference,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, checker_metadata.as_ref());
                Some(Default::default())
            },
        )
    }
}
