// Generated by TEPL from checked concrete rules.
#![allow(unused_imports, unused_variables, unused_mut, unused_parens)]

pub mod rule_commute_add {
    use super::super::super::pattern::{AnalysisMetadata, RewriteAnalysis};
    use super::super::super::pattern::{
        AttrExpr, AttrPattern, AttrVar, DTypeConstraint, MatchBinding, MatchChecks, MatchContext,
        MetadataBindings, ShapePart, TensorConstraint, TensorConstraints, TensorExpr, TensorInfo,
        TensorPattern, tensor_rewrite_with_checks,
    };
    use super::super::super::{DType, OpAttrs, OpNode};
    use ::egg::{EGraph, Rewrite, Var};
    use ::std::collections::HashMap;
    pub trait Functions: Send + Sync {}
    impl Functions for () {}
    pub fn pattern() -> TensorPattern {
        TensorPattern::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrPattern::Exact(OpAttrs::None),
            vec![
                TensorPattern::Var("?c0".parse::<Var>().expect("generated capture ID")),
                TensorPattern::Var("?c1".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn expression() -> TensorExpr {
        TensorExpr::op(
            super::super::super::dialects::tensor_lang::Op::Add,
            AttrExpr::Exact(OpAttrs::None),
            vec![
                TensorExpr::Var("?c1".parse::<Var>().expect("generated capture ID")),
                TensorExpr::Var("?c0".parse::<Var>().expect("generated capture ID")),
            ],
        )
    }
    pub fn constraints() -> TensorConstraints {
        TensorConstraints::new(vec![])
    }
    /// Shape declarations and the ordered builtin-only where prefix.
    pub fn match_checks<N: RewriteAnalysis>() -> MatchChecks<N> {
        MatchChecks::tensors(constraints())
    }
    /// Uses the graph's analysis; () supports structural rules.
    pub fn build_rewrite<N, F>(functions: F) -> Result<Rewrite<OpNode, N>, String>
    where
        N: RewriteAnalysis,
        F: Functions + 'static,
    {
        let checks = match_checks::<N>();
        let metadata = AnalysisMetadata::<N>::new();
        tensor_rewrite_with_checks(
            "simple::commute_add",
            pattern(),
            expression(),
            checks,
            false,
            move |graph, matched, dimensions| {
                let ctx = MatchContext::new(graph, matched, &metadata);
                Some(Default::default())
            },
        )
    }
}
