load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ir",
    srcs = [
        "dtype_policy.cc",
        "literal.cc",
        "shape/builtins.cc",
        "shape/types.cc",
        "types.cc",
    ],
    hdrs = [
        "dtype_policy.h",
        "ids.h",
        "ir.h",
        "literal.h",
        "shape/builtins.h",
        "shape/ir.h",
        "shape/types.h",
        "types.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:operators",
        "//:source",
    ],
)

cc_library(
    name = "analysis",
    srcs = [
        "analysis_context.cc",
        "analysis_context.h",
        "analyze.cc",
        "dialect/attributes.cc",
        "dialect/attributes.h",
        "dialect/check.cc",
        "dialect/check.h",
        "dialect/symbols.h",
        "resolution/file_scope.cc",
        "resolution/file_scope.h",
        "resolution/resolve.cc",
        "resolution/resolve.h",
        "resolution/source.cc",
        "resolution/source.h",
        "rule/check.cc",
        "rule/check.h",
        "rule/check_context.h",
        "rule/declarations.cc",
        "rule/declarations.h",
        "rule/descriptors.cc",
        "rule/descriptors.h",
        "rule/expand.cc",
        "rule/expand.h",
        "rule/expanded_rule.h",
        "rule/expression.cc",
        "rule/expression.h",
        "rule/graph.cc",
        "rule/graph.h",
        "rule/resolve.cc",
        "rule/resolve.h",
        "rule/scope.h",
        "shape/check.cc",
        "shape/check.h",
        "shape/check_context.h",
        "shape/expression.cc",
        "shape/expression.h",
        "shape/type_inference.cc",
        "shape/type_inference.h",
        "type_inference.cc",
        "type_inference.h",
    ],
    hdrs = [
        "analyze.h",
        "diagnostic.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":ir",
        "//:source",
        "//src/ast:ast",
    ],
)

cc_library(
    name = "print",
    srcs = ["print.cc", "shape/print.cc"],
    hdrs = ["print.h", "shape/print.h"],
    visibility = ["//visibility:public"],
    deps = [":ir"],
)
