load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ir",
    srcs = [
        "builtins/catalog.cc",
        "metadata/types.cc",
        "type/literal.cc",
        "type/types.cc",
    ],
    hdrs = [
        "builtins/catalog.h",
        "ids.h",
        "ir.h",
        "metadata/ir.h",
        "metadata/types.h",
        "type/literal.h",
        "type/types.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:operators",
        "//:source",
    ],
)

cc_library(
    name = "analysis",
    srcs = [
        "analysis_context.cc",
        "analysis_context.h",
        "analyze.cc",
        "graph/check.cc",
        "graph/check.h",
        "dialect/attributes.cc",
        "dialect/attributes.h",
        "dialect/check.cc",
        "dialect/check.h",
        "dialect/symbols.h",
        "resolution/file_scope.cc",
        "resolution/file_scope.h",
        "resolution/resolve.cc",
        "resolution/resolve.h",
        "resolution/source.cc",
        "resolution/source.h",
        "rule/check.cc",
        "rule/check.h",
        "rule/check_context.h",
        "rule/declarations.cc",
        "rule/declarations.h",
        "rule/descriptors.cc",
        "rule/descriptors.h",
        "rule/expand.cc",
        "rule/expand.h",
        "rule/expanded_rule.h",
        "rule/expression.cc",
        "rule/expression.h",
        "rule/graph.cc",
        "rule/graph.h",
        "rule/resolve.cc",
        "rule/resolve.h",
        "rule/scope.h",
        "metadata/check.cc",
        "metadata/check.h",
        "metadata/check_context.h",
        "metadata/expression.cc",
        "metadata/expression.h",
        "metadata/type_inference.cc",
        "metadata/type_inference.h",
        "type/type_inference.cc",
        "type/type_inference.h",
    ],
    hdrs = [
        "analyze.h",
        "diagnostic.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":ir",
        "//:source",
        "//src/ast:ast",
    ],
)

cc_library(
    name = "print",
    srcs = ["print.cc", "metadata/print.cc"],
    hdrs = ["print.h", "metadata/print.h"],
    visibility = ["//visibility:public"],
    deps = [":ir"],
)
