// Generated by TEPL from checked operation definitions.
#![allow(unused_imports, unused_variables, unused_parens, unreachable_code)]
use super::super::{DType, Op, OpAttrs};
use super::Inference;
pub fn infer_dtype(op: Op, operands: &[DType], attrs: &OpAttrs) -> Inference<DType> {
    if !op.arity().accepts(operands.len()) || !op.accepts_attrs(attrs) {
        return Inference::Invalid(
            "operand count or attributes do not match the operation signature",
        );
    }
    match op {
        Op::Input => Inference::Unknown,
        Op::Literal => {
            let OpAttrs::Literal { dtype, .. } = attrs else {
                unreachable!()
            };
            dtype.map(Inference::Known).unwrap_or(Inference::Unknown)
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::Equal) => {
            match dtype_0(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::Convert) => {
            match dtype_1(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::Select) => {
            match dtype_2(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::ScalarZero) => {
            match dtype_3(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::Scalar(super::super::dialects::scalar::Op::Add) => match dtype_4(operands, attrs) {
            Ok(dtype) => Inference::Known(dtype),
            Err(error) => Inference::Invalid(error.message()),
        },
        Op::Scalar(super::super::dialects::scalar::Op::Negate) => match dtype_5(operands, attrs) {
            Ok(dtype) => Inference::Known(dtype),
            Err(error) => Inference::Invalid(error.message()),
        },
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Add) => {
            match dtype_6(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Subtract) => {
            match dtype_7(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Multiply) => {
            match dtype_8(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Divide) => {
            match dtype_9(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Maximum) => {
            match dtype_10(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Minimum) => {
            match dtype_11(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Negate) => {
            match dtype_12(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Exponential) => {
            match dtype_13(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Log) => {
            match dtype_14(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Abs) => {
            match dtype_15(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Sqrt) => {
            match dtype_16(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Rsqrt) => {
            match dtype_17(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Reshape) => {
            match dtype_18(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Transpose) => {
            match dtype_19(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::BroadcastInDim) => {
            match dtype_20(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Slice) => {
            match dtype_21(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Concatenate) => {
            match dtype_22(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Reduce) => {
            match dtype_23(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::DotGeneral) => Inference::Unknown,
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Convolution) => Inference::Unknown,
        Op::TensorLang(super::super::dialects::tensor_lang::Op::AllGather) => {
            match dtype_26(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::AllReduce) => {
            match dtype_27(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::ReduceScatter) => {
            match dtype_28(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::AllToAll) => {
            match dtype_29(operands, attrs) {
                Ok(dtype) => Inference::Known(dtype),
                Err(error) => Inference::Invalid(error.message()),
            }
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Constant) => Inference::Unknown,
    }
}
/// TEPL dtype program for DTypeExamples.equal.
fn dtype_0(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "DTypeExamples.equal dtype assertion at 5:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "DTypeExamples.equal dtype assertion at 6:13",
    )?;
    Ok(DType::Bool)
}
/// TEPL dtype program for DTypeExamples.convert.
fn dtype_1(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::DTypeExamples(super::super::dialects::d_type_examples::OpAttrs::ConvertAttrs {
        to: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: super::super::DType = field_0.clone();
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "DTypeExamples.convert dtype assertion at 22:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(attribute_0),
        "DTypeExamples.convert dtype assertion at 23:13",
    )?;
    Ok(attribute_0)
}
/// TEPL dtype program for DTypeExamples.select.
fn dtype_2(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    let symbol_2: super::super::DType = operands[2];
    super::super::builtins::common::ensure(
        (symbol_0 == DType::Bool),
        "DTypeExamples.select dtype assertion at 33:13",
    )?;
    super::super::builtins::common::ensure(
        (symbol_1 == symbol_2),
        "DTypeExamples.select dtype assertion at 34:13",
    )?;
    Ok(symbol_1)
}
/// TEPL dtype program for DTypeExamples.scalar_zero.
fn dtype_3(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    Ok(DType::F32)
}
/// TEPL dtype program for Scalar.add.
fn dtype_4(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "Scalar.add dtype assertion at 6:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "Scalar.add dtype assertion at 7:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for Scalar.negate.
fn dtype_5(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "Scalar.negate dtype assertion at 17:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.add.
fn dtype_6(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.add dtype assertion at 16:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.add dtype assertion at 17:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.subtract.
fn dtype_7(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.subtract dtype assertion at 27:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.subtract dtype assertion at 28:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.multiply.
fn dtype_8(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.multiply dtype assertion at 38:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.multiply dtype assertion at 39:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.divide.
fn dtype_9(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.divide dtype assertion at 50:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.divide dtype assertion at 51:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.maximum.
fn dtype_10(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.maximum dtype assertion at 61:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.maximum dtype assertion at 62:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.minimum.
fn dtype_11(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.minimum dtype assertion at 72:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.minimum dtype assertion at 73:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.negate.
fn dtype_12(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.negate dtype assertion at 84:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.exponential.
fn dtype_13(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_float(symbol_0),
        "TensorLang.exponential dtype assertion at 93:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.log.
fn dtype_14(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_float(symbol_0),
        "TensorLang.log dtype assertion at 103:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.abs.
fn dtype_15(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_numeric(symbol_0),
        "TensorLang.abs dtype assertion at 112:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.sqrt.
fn dtype_16(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_float(symbol_0),
        "TensorLang.sqrt dtype assertion at 121:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.rsqrt.
fn dtype_17(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    super::super::builtins::common::ensure(
        super::super::builtins::dtype::is_float(symbol_0),
        "TensorLang.rsqrt dtype assertion at 130:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.reshape.
fn dtype_18(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ReshapeAttrs {
        shape: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.transpose.
fn dtype_19(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::TransposeAttrs {
        permutation: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.broadcast_in_dim.
fn dtype_20(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::BroadcastInDimAttrs {
        broadcast_dimensions: field_0,
        shape: field_1,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_1: Vec<i128> = field_1
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.slice.
fn dtype_21(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::SliceAttrs {
        start_indices: field_0,
        limit_indices: field_1,
        strides: field_2,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_1: Vec<i128> = field_1
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_2: Vec<i128> = field_2
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.concatenate.
fn dtype_22(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: Vec<super::super::DType> = operands[0..].to_vec();
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ConcatenateAttrs {
        dimension: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: i128 = i128::from(*field_0);
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_0.clone())) as i128) > 0_i128),
        "TensorLang.concatenate dtype assertion at 205:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((symbol_0.clone())
                .into_iter()
                .map(|symbol_1| -> super::super::builtins::BuiltinResult<bool> {
                    Ok((symbol_1
                        == super::super::builtins::common::index(&(symbol_0.clone()), 0_i128)?
                            .clone()))
                })
                .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.concatenate dtype assertion at 206:13",
    )?;
    Ok(super::super::builtins::common::index(&(symbol_0.clone()), 0_i128)?.clone())
}
/// TEPL dtype program for TensorLang.reduce.
fn dtype_23(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let symbol_1: super::super::DType = operands[1];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ReduceAttrs {
        dimensions: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    super::super::builtins::common::ensure(
        (symbol_0 == symbol_1),
        "TensorLang.reduce dtype assertion at 227:13",
    )?;
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.all_gather.
fn dtype_26(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::AllGatherAttrs {
        all_gather_dim: field_0,
        channel_id: field_2,
        use_global_device_ids: field_3,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: i128 = i128::from(*field_0);
    let attribute_2: i128 = i128::from(*field_2);
    let attribute_3: bool = field_3.clone();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.all_reduce.
fn dtype_27(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::CollectiveReduce {
        channel_id: field_1,
        use_global_device_ids: field_2,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_1: i128 = i128::from(*field_1);
    let attribute_2: bool = field_2.clone();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.reduce_scatter.
fn dtype_28(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ReduceScatterAttrs {
        scatter_dimension: field_0,
        channel_id: field_2,
        use_global_device_ids: field_3,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: i128 = i128::from(*field_0);
    let attribute_2: i128 = i128::from(*field_2);
    let attribute_3: bool = field_3.clone();
    Ok(symbol_0)
}
/// TEPL dtype program for TensorLang.all_to_all.
fn dtype_29(operands: &[DType], attrs: &OpAttrs) -> super::super::builtins::BuiltinResult<DType> {
    let symbol_0: super::super::DType = operands[0];
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::AllToAllAttrs {
        split_dimension: field_0,
        concat_dimension: field_1,
        split_count: field_2,
        channel_id: field_4,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: i128 = i128::from(*field_0);
    let attribute_1: i128 = i128::from(*field_1);
    let attribute_2: i128 = i128::from(*field_2);
    let attribute_4: i128 = i128::from(*field_4);
    Ok(symbol_0)
}
