// Generated by TEPL from checked operation definitions.
#![allow(unused_imports, unused_variables, unused_parens, unreachable_code)]
use super::super::{DType, Op, OpAttrs};
use super::Inference;
pub fn infer_shape(op: Op, operands: &[&[u64]], attrs: &OpAttrs) -> Inference<Vec<u64>> {
    if !op.arity().accepts(operands.len()) || !op.accepts_attrs(attrs) {
        return Inference::Invalid(
            "operand count or attributes do not match the operation signature",
        );
    }
    let result: super::super::builtins::BuiltinResult<Vec<u64>> = match op {
        Op::Input => return Inference::Unknown,
        Op::Literal => return Inference::Known(vec![]),
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::Equal) => {
            shape_0(operands, attrs)
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::Convert) => {
            shape_1(operands, attrs)
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::Select) => {
            shape_2(operands, attrs)
        }
        Op::DTypeExamples(super::super::dialects::d_type_examples::Op::ScalarZero) => {
            shape_3(operands, attrs)
        }
        Op::Scalar(super::super::dialects::scalar::Op::Add) => shape_4(operands, attrs),
        Op::Scalar(super::super::dialects::scalar::Op::Negate) => shape_5(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Add) => shape_6(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Subtract) => {
            shape_7(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Multiply) => {
            shape_8(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Divide) => shape_9(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Maximum) => {
            shape_10(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Minimum) => {
            shape_11(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Negate) => {
            shape_12(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Exponential) => {
            shape_13(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Log) => shape_14(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Abs) => shape_15(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Sqrt) => shape_16(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Rsqrt) => shape_17(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Reshape) => {
            shape_18(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Transpose) => {
            shape_19(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::BroadcastInDim) => {
            shape_20(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Slice) => shape_21(operands, attrs),
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Concatenate) => {
            shape_22(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Reduce) => {
            shape_23(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::DotGeneral) => {
            shape_24(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Convolution) => {
            shape_25(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::AllGather) => {
            return Inference::Unknown;
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::AllReduce) => {
            shape_27(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::ReduceScatter) => {
            return Inference::Unknown;
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::AllToAll) => {
            shape_29(operands, attrs)
        }
        Op::TensorLang(super::super::dialects::tensor_lang::Op::Constant) => {
            return Inference::Unknown;
        }
    };
    match result {
        Ok(shape) => Inference::Known(shape),
        Err(error) => Inference::Invalid(error.message()),
    }
}
/// TEPL shape program for DTypeExamples.equal.
fn shape_0(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "DTypeExamples.equal shape assertion at 10:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for DTypeExamples.convert.
fn shape_1(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::DTypeExamples(super::super::dialects::d_type_examples::OpAttrs::ConvertAttrs {
        to: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: super::super::DType = field_0.clone();
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for DTypeExamples.select.
fn shape_2(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    let symbol_2: Vec<i128> = super::super::builtins::shape::integers(operands[2]);
    super::super::builtins::common::ensure(
        ((symbol_0.clone() == symbol_1.clone()) && (symbol_1.clone() == symbol_2.clone())),
        "DTypeExamples.select shape assertion at 38:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_1.clone()))
}
/// TEPL shape program for DTypeExamples.scalar_zero.
fn shape_3(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    super::super::builtins::shape::dimensions(&(Vec::<i128>::from([])))
}
/// TEPL shape program for Scalar.add.
fn shape_4(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        ((symbol_0.clone() == Vec::<i128>::from([]))
            && (symbol_1.clone() == Vec::<i128>::from([]))),
        "Scalar.add shape assertion at 11:13",
    )?;
    super::super::builtins::shape::dimensions(&(Vec::<i128>::from([])))
}
/// TEPL shape program for Scalar.negate.
fn shape_5(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == Vec::<i128>::from([])),
        "Scalar.negate shape assertion at 21:13",
    )?;
    super::super::builtins::shape::dimensions(&(Vec::<i128>::from([])))
}
/// TEPL shape program for TensorLang.add.
fn shape_6(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "TensorLang.add shape assertion at 21:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.subtract.
fn shape_7(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "TensorLang.subtract shape assertion at 32:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.multiply.
fn shape_8(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "TensorLang.multiply shape assertion at 44:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.divide.
fn shape_9(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "TensorLang.divide shape assertion at 55:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.maximum.
fn shape_10(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "TensorLang.maximum shape assertion at 66:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.minimum.
fn shape_11(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    super::super::builtins::common::ensure(
        (symbol_0.clone() == symbol_1.clone()),
        "TensorLang.minimum shape assertion at 77:13",
    )?;
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.negate.
fn shape_12(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.exponential.
fn shape_13(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.log.
fn shape_14(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.abs.
fn shape_15(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.sqrt.
fn shape_16(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.rsqrt.
fn shape_17(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.reshape.
fn shape_18(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ReshapeAttrs {
        shape: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    super::super::builtins::common::ensure(
        (super::super::builtins::common::product(&(symbol_0.clone()))?
            == super::super::builtins::common::product(&(attribute_0.clone()))?),
        "TensorLang.reshape shape assertion at 147:13",
    )?;
    super::super::builtins::shape::dimensions(&(attribute_0.clone()))
}
/// TEPL shape program for TensorLang.transpose.
fn shape_19(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::TransposeAttrs {
        permutation: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(attribute_0.clone()),
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        ),
        "TensorLang.transpose shape assertion at 159:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_0.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_0.clone())) as i128)),
        "TensorLang.transpose shape assertion at 160:13",
    )?;
    super::super::builtins::shape::dimensions(
        &(super::super::builtins::common::gather(&(symbol_0.clone()), &(attribute_0.clone()))?),
    )
}
/// TEPL shape program for TensorLang.broadcast_in_dim.
fn shape_20(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::BroadcastInDimAttrs {
        broadcast_dimensions: field_0,
        shape: field_1,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_1: Vec<i128> = field_1
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_0.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_0.clone())) as i128)),
        "TensorLang.broadcast_in_dim shape assertion at 174:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(attribute_0.clone()),
            (super::super::builtins::common::len(&(attribute_1.clone())) as i128),
        ),
        "TensorLang.broadcast_in_dim shape assertion at 175:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((super::super::builtins::shape::integers(&super::super::builtins::common::range(
                (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
            )?))
            .into_iter()
            .map(|symbol_1| -> super::super::builtins::BuiltinResult<bool> {
                Ok(
                    ((super::super::builtins::common::index(&(symbol_0.clone()), symbol_1)?
                        .clone()
                        == 1_i128)
                        || (super::super::builtins::common::index(&(symbol_0.clone()), symbol_1)?
                            .clone()
                            == super::super::builtins::common::index(
                                &(attribute_1.clone()),
                                super::super::builtins::common::index(
                                    &(attribute_0.clone()),
                                    symbol_1,
                                )?
                                .clone(),
                            )?
                            .clone())),
                )
            })
            .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.broadcast_in_dim shape assertion at 176:13",
    )?;
    super::super::builtins::shape::dimensions(&(attribute_1.clone()))
}
/// TEPL shape program for TensorLang.slice.
fn shape_21(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::SliceAttrs {
        start_indices: field_0,
        limit_indices: field_1,
        strides: field_2,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_1: Vec<i128> = field_1
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_2: Vec<i128> = field_2
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_0.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_0.clone())) as i128)),
        "TensorLang.slice shape assertion at 191:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_1.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_0.clone())) as i128)),
        "TensorLang.slice shape assertion at 192:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_2.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_0.clone())) as i128)),
        "TensorLang.slice shape assertion at 193:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((super::super::builtins::shape::integers(&super::super::builtins::common::range(
                (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
            )?))
            .into_iter()
            .map(|symbol_1| -> super::super::builtins::BuiltinResult<bool> {
                Ok(
                    (((super::super::builtins::common::index(&(attribute_0.clone()), symbol_1)?
                        .clone()
                        <= super::super::builtins::common::index(
                            &(attribute_1.clone()),
                            symbol_1,
                        )?
                        .clone())
                        && (super::super::builtins::common::index(
                            &(attribute_1.clone()),
                            symbol_1,
                        )?
                        .clone()
                            <= super::super::builtins::common::index(
                                &(symbol_0.clone()),
                                symbol_1,
                            )?
                            .clone()))
                        && (super::super::builtins::common::index(
                            &(attribute_2.clone()),
                            symbol_1,
                        )?
                        .clone()
                            > 0_i128)),
                )
            })
            .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.slice shape assertion at 194:13",
    )?;
    super::super::builtins::shape::dimensions(
        &((super::super::builtins::shape::integers(&super::super::builtins::common::range(
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        )?))
        .into_iter()
        .map(|symbol_2| -> super::super::builtins::BuiltinResult<i128> {
            Ok(super::super::builtins::common::ceil_div(
                super::super::builtins::common::sub(
                    super::super::builtins::common::index(&(attribute_1.clone()), symbol_2)?
                        .clone(),
                    super::super::builtins::common::index(&(attribute_0.clone()), symbol_2)?
                        .clone(),
                )?,
                super::super::builtins::common::index(&(attribute_2.clone()), symbol_2)?.clone(),
            )?)
        })
        .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?),
    )
}
/// TEPL shape program for TensorLang.concatenate.
fn shape_22(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<Vec<i128>> = operands[0..]
        .iter()
        .map(|shape| super::super::builtins::shape::integers(shape))
        .collect::<Vec<_>>();
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ConcatenateAttrs {
        dimension: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: i128 = i128::from(*field_0);
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_0.clone())) as i128) > 0_i128),
        "TensorLang.concatenate shape assertion at 213:13",
    )?;
    let symbol_1: Vec<i128> =
        super::super::builtins::common::index(&(symbol_0.clone()), 0_i128)?.clone();
    let symbol_2: i128 = attribute_0;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(Vec::<i128>::from([symbol_2])),
            (super::super::builtins::common::len(&(symbol_1.clone())) as i128),
        ),
        "TensorLang.concatenate shape assertion at 216:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((symbol_0.clone())
                .into_iter()
                .map(|symbol_3| -> super::super::builtins::BuiltinResult<bool> {
                    Ok(
                        ((super::super::builtins::common::len(&(symbol_3.clone())) as i128)
                            == (super::super::builtins::common::len(&(symbol_1.clone())) as i128)),
                    )
                })
                .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.concatenate shape assertion at 217:13",
    )?;
    let symbol_4: Vec<i128> = super::super::builtins::common::exclude(
        &(super::super::builtins::shape::integers(&super::super::builtins::common::range(
            (super::super::builtins::common::len(&(symbol_1.clone())) as i128),
        )?)),
        &(Vec::<i128>::from([symbol_2])),
    );
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((symbol_0.clone())
                .into_iter()
                .map(|symbol_5| -> super::super::builtins::BuiltinResult<bool> {
                    Ok((super::super::builtins::common::gather(
                        &(symbol_5.clone()),
                        &(symbol_4.clone()),
                    )? == super::super::builtins::common::gather(
                        &(symbol_1.clone()),
                        &(symbol_4.clone()),
                    )?))
                })
                .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.concatenate shape assertion at 219:13",
    )?;
    super::super::builtins::shape::dimensions(
        &(super::super::builtins::common::replace(
            &(symbol_1.clone()),
            symbol_2,
            super::super::builtins::common::sum(
                &((symbol_0.clone())
                    .into_iter()
                    .map(|symbol_6| -> super::super::builtins::BuiltinResult<i128> {
                        Ok(
                            super::super::builtins::common::index(&(symbol_6.clone()), symbol_2)?
                                .clone(),
                        )
                    })
                    .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?),
            )?,
        )?),
    )
}
/// TEPL shape program for TensorLang.reduce.
fn shape_23(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ReduceAttrs {
        dimensions: field_0,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    super::super::builtins::common::ensure(
        (symbol_1.clone() == Vec::<i128>::from([])),
        "TensorLang.reduce shape assertion at 236:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(attribute_0.clone()),
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        ),
        "TensorLang.reduce shape assertion at 237:13",
    )?;
    super::super::builtins::shape::dimensions(
        &(super::super::builtins::common::gather(
            &(symbol_0.clone()),
            &(super::super::builtins::common::exclude(
                &(super::super::builtins::shape::integers(&super::super::builtins::common::range(
                    (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
                )?)),
                &(attribute_0.clone()),
            )),
        )?),
    )
}
/// TEPL shape program for TensorLang.dot_general.
fn shape_24(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::DotGeneralAttrs {
        lhs_contracting_dimensions: field_0,
        rhs_contracting_dimensions: field_1,
        lhs_batching_dimensions: field_2,
        rhs_batching_dimensions: field_3,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_1: Vec<i128> = field_1
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_2: Vec<i128> = field_2
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_3: Vec<i128> = field_3
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let symbol_2: Vec<i128> = attribute_0.clone();
    let symbol_3: Vec<i128> = attribute_1.clone();
    let symbol_4: Vec<i128> = attribute_2.clone();
    let symbol_5: Vec<i128> = attribute_3.clone();
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(symbol_2.clone()),
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        ),
        "TensorLang.dot_general shape assertion at 258:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(symbol_3.clone()),
            (super::super::builtins::common::len(&(symbol_1.clone())) as i128),
        ),
        "TensorLang.dot_general shape assertion at 259:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(symbol_4.clone()),
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        ),
        "TensorLang.dot_general shape assertion at 260:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(symbol_5.clone()),
            (super::super::builtins::common::len(&(symbol_1.clone())) as i128),
        ),
        "TensorLang.dot_general shape assertion at 261:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::is_disjoint(&(symbol_4.clone()), &(symbol_2.clone())),
        "TensorLang.dot_general shape assertion at 262:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::is_disjoint(&(symbol_5.clone()), &(symbol_3.clone())),
        "TensorLang.dot_general shape assertion at 263:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_4.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_5.clone())) as i128)),
        "TensorLang.dot_general shape assertion at 264:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_2.clone())) as i128)
            == (super::super::builtins::common::len(&(symbol_3.clone())) as i128)),
        "TensorLang.dot_general shape assertion at 265:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::gather(&(symbol_0.clone()), &(symbol_4.clone()))?
            == super::super::builtins::common::gather(&(symbol_1.clone()), &(symbol_5.clone()))?),
        "TensorLang.dot_general shape assertion at 266:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::gather(&(symbol_0.clone()), &(symbol_2.clone()))?
            == super::super::builtins::common::gather(&(symbol_1.clone()), &(symbol_3.clone()))?),
        "TensorLang.dot_general shape assertion at 267:13",
    )?;
    let symbol_6: Vec<i128> = super::super::builtins::common::exclude(
        &(super::super::builtins::shape::integers(&super::super::builtins::common::range(
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        )?)),
        &(super::super::builtins::common::concat(&[&(symbol_4.clone()), &(symbol_2.clone())])?),
    );
    let symbol_7: Vec<i128> = super::super::builtins::common::exclude(
        &(super::super::builtins::shape::integers(&super::super::builtins::common::range(
            (super::super::builtins::common::len(&(symbol_1.clone())) as i128),
        )?)),
        &(super::super::builtins::common::concat(&[&(symbol_5.clone()), &(symbol_3.clone())])?),
    );
    super::super::builtins::shape::dimensions(
        &(super::super::builtins::common::concat(&[
            &(super::super::builtins::common::gather(&(symbol_0.clone()), &(symbol_4.clone()))?),
            &(super::super::builtins::common::gather(&(symbol_0.clone()), &(symbol_6.clone()))?),
            &(super::super::builtins::common::gather(&(symbol_1.clone()), &(symbol_7.clone()))?),
        ])?),
    )
}
/// TEPL shape program for TensorLang.convolution.
fn shape_25(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let symbol_1: Vec<i128> = super::super::builtins::shape::integers(operands[1]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::ConvolutionAttrs {
        window_strides: field_0,
        padding: field_1,
        lhs_dilation: field_2,
        rhs_dilation: field_3,
        window_reversal: field_4,
        input_batch_dimension: field_5,
        input_feature_dimension: field_6,
        input_spatial_dimensions: field_7,
        kernel_input_feature_dimension: field_8,
        kernel_output_feature_dimension: field_9,
        kernel_spatial_dimensions: field_10,
        output_batch_dimension: field_11,
        output_feature_dimension: field_12,
        output_spatial_dimensions: field_13,
        feature_group_count: field_14,
        batch_group_count: field_15,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: Vec<i128> = field_0
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_1: Vec<Vec<i128>> = field_1
        .iter()
        .map(|item_2| {
            item_2
                .iter()
                .map(|item_1| i128::from(*item_1))
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    let attribute_2: Vec<i128> = field_2
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_3: Vec<i128> = field_3
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_4: Vec<bool> = field_4.clone();
    let attribute_5: i128 = i128::from(*field_5);
    let attribute_6: i128 = i128::from(*field_6);
    let attribute_7: Vec<i128> = field_7
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_8: i128 = i128::from(*field_8);
    let attribute_9: i128 = i128::from(*field_9);
    let attribute_10: Vec<i128> = field_10
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_11: i128 = i128::from(*field_11);
    let attribute_12: i128 = i128::from(*field_12);
    let attribute_13: Vec<i128> = field_13
        .iter()
        .map(|item_1| i128::from(*item_1))
        .collect::<Vec<_>>();
    let attribute_14: i128 = i128::from(*field_14);
    let attribute_15: i128 = i128::from(*field_15);
    let symbol_2: i128 = (super::super::builtins::common::len(&(symbol_0.clone())) as i128);
    super::super::builtins::common::ensure(
        ((symbol_2 >= 2_i128)
            && ((super::super::builtins::common::len(&(symbol_1.clone())) as i128) == symbol_2)),
        "TensorLang.convolution shape assertion at 296:13",
    )?;
    let symbol_3: i128 = super::super::builtins::common::sub(symbol_2, 2_i128)?;
    let symbol_4: Vec<i128> =
        super::super::builtins::shape::integers(&super::super::builtins::common::range(symbol_3)?);
    let symbol_5: Vec<i128> = attribute_7.clone();
    let symbol_6: Vec<i128> = attribute_10.clone();
    let symbol_7: Vec<i128> = attribute_13.clone();
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_5.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 302:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_6.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 303:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(symbol_7.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 304:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(super::super::builtins::common::concat(&[
                &(Vec::<i128>::from([attribute_5])),
                &(symbol_5.clone()),
                &(Vec::<i128>::from([attribute_6])),
            ])?),
            symbol_2,
        ),
        "TensorLang.convolution shape assertion at 305:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(super::super::builtins::common::concat(&[
                &(Vec::<i128>::from([attribute_8])),
                &(symbol_6.clone()),
                &(Vec::<i128>::from([attribute_9])),
            ])?),
            symbol_2,
        ),
        "TensorLang.convolution shape assertion at 307:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(super::super::builtins::common::concat(&[
                &(Vec::<i128>::from([attribute_11])),
                &(symbol_7.clone()),
                &(Vec::<i128>::from([attribute_12])),
            ])?),
            symbol_2,
        ),
        "TensorLang.convolution shape assertion at 309:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_0.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 311:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_1.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 312:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((attribute_1.clone())
                .into_iter()
                .map(|symbol_8| -> super::super::builtins::BuiltinResult<bool> {
                    Ok(
                        ((super::super::builtins::common::len(&(symbol_8.clone())) as i128)
                            == 2_i128),
                    )
                })
                .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.convolution shape assertion at 313:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_2.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 314:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_3.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 315:13",
    )?;
    super::super::builtins::common::ensure(
        ((super::super::builtins::common::len(&(attribute_4.clone())) as i128) == symbol_3),
        "TensorLang.convolution shape assertion at 316:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::common::all(
            &((symbol_4.clone())
                .into_iter()
                .map(|symbol_9| -> super::super::builtins::BuiltinResult<bool> {
                    Ok((((super::super::builtins::common::index(
                        &(attribute_0.clone()),
                        symbol_9,
                    )?
                    .clone()
                        > 0_i128)
                        && (super::super::builtins::common::index(
                            &(attribute_2.clone()),
                            symbol_9,
                        )?
                        .clone()
                            > 0_i128))
                        && (super::super::builtins::common::index(
                            &(attribute_3.clone()),
                            symbol_9,
                        )?
                        .clone()
                            > 0_i128)))
                })
                .collect::<super::super::builtins::BuiltinResult<Vec<bool>>>()?),
        ),
        "TensorLang.convolution shape assertion at 317:13",
    )?;
    let symbol_10: i128 = attribute_14;
    let symbol_11: i128 = attribute_15;
    super::super::builtins::common::ensure(
        ((symbol_10 > 0_i128) && (symbol_11 > 0_i128)),
        "TensorLang.convolution shape assertion at 322:13",
    )?;
    super::super::builtins::common::ensure(
        ((symbol_10 == 1_i128) || (symbol_11 == 1_i128)),
        "TensorLang.convolution shape assertion at 323:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::rem(
            super::super::builtins::common::index(&(symbol_0.clone()), attribute_5)?.clone(),
            symbol_11,
        )? == 0_i128),
        "TensorLang.convolution shape assertion at 324:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::rem(
            super::super::builtins::common::index(&(symbol_0.clone()), attribute_6)?.clone(),
            symbol_10,
        )? == 0_i128),
        "TensorLang.convolution shape assertion at 325:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::index(&(symbol_1.clone()), attribute_8)?.clone()
            == super::super::builtins::common::div(
                super::super::builtins::common::index(&(symbol_0.clone()), attribute_6)?.clone(),
                symbol_10,
            )?),
        "TensorLang.convolution shape assertion at 326:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::rem(
            super::super::builtins::common::index(&(symbol_1.clone()), attribute_9)?.clone(),
            symbol_11,
        )? == 0_i128),
        "TensorLang.convolution shape assertion at 328:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::rem(
            super::super::builtins::common::index(&(symbol_1.clone()), attribute_9)?.clone(),
            symbol_10,
        )? == 0_i128),
        "TensorLang.convolution shape assertion at 329:13",
    )?;
    let symbol_13: Vec<i128> = (symbol_4.clone())
        .into_iter()
        .map(|symbol_12| -> super::super::builtins::BuiltinResult<i128> {
            Ok((if (super::super::builtins::common::index(
                &(symbol_0.clone()),
                super::super::builtins::common::index(&(symbol_5.clone()), symbol_12)?.clone(),
            )?
            .clone()
                == 0_i128)
            {
                0_i128
            } else {
                super::super::builtins::common::add(
                    super::super::builtins::common::mul(
                        super::super::builtins::common::sub(
                            super::super::builtins::common::index(
                                &(symbol_0.clone()),
                                super::super::builtins::common::index(
                                    &(symbol_5.clone()),
                                    symbol_12,
                                )?
                                .clone(),
                            )?
                            .clone(),
                            1_i128,
                        )?,
                        super::super::builtins::common::index(&(attribute_2.clone()), symbol_12)?
                            .clone(),
                    )?,
                    1_i128,
                )?
            }))
        })
        .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?;
    let symbol_15: Vec<i128> = (symbol_4.clone())
        .into_iter()
        .map(|symbol_14| -> super::super::builtins::BuiltinResult<i128> {
            Ok(super::super::builtins::common::add(
                super::super::builtins::common::add(
                    super::super::builtins::common::index(
                        &(super::super::builtins::common::index(
                            &(attribute_1.clone()),
                            symbol_14,
                        )?
                        .clone()),
                        0_i128,
                    )?
                    .clone(),
                    super::super::builtins::common::index(&(symbol_13.clone()), symbol_14)?.clone(),
                )?,
                super::super::builtins::common::index(
                    &(super::super::builtins::common::index(&(attribute_1.clone()), symbol_14)?
                        .clone()),
                    1_i128,
                )?
                .clone(),
            )?)
        })
        .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?;
    let symbol_17: Vec<i128> = (symbol_4.clone())
        .into_iter()
        .map(|symbol_16| -> super::super::builtins::BuiltinResult<i128> {
            Ok((if (super::super::builtins::common::index(
                &(symbol_1.clone()),
                super::super::builtins::common::index(&(symbol_6.clone()), symbol_16)?.clone(),
            )?
            .clone()
                == 0_i128)
            {
                0_i128
            } else {
                super::super::builtins::common::add(
                    super::super::builtins::common::mul(
                        super::super::builtins::common::sub(
                            super::super::builtins::common::index(
                                &(symbol_1.clone()),
                                super::super::builtins::common::index(
                                    &(symbol_6.clone()),
                                    symbol_16,
                                )?
                                .clone(),
                            )?
                            .clone(),
                            1_i128,
                        )?,
                        super::super::builtins::common::index(&(attribute_3.clone()), symbol_16)?
                            .clone(),
                    )?,
                    1_i128,
                )?
            }))
        })
        .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?;
    let symbol_19: Vec<i128> = (symbol_4.clone())
        .into_iter()
        .map(|symbol_18| -> super::super::builtins::BuiltinResult<i128> {
            Ok(
                (if ((super::super::builtins::common::index(&(symbol_15.clone()), symbol_18)?
                    .clone()
                    == 0_i128)
                    || (super::super::builtins::common::index(&(symbol_17.clone()), symbol_18)?
                        .clone()
                        > super::super::builtins::common::index(&(symbol_15.clone()), symbol_18)?
                            .clone()))
                {
                    0_i128
                } else {
                    super::super::builtins::common::add(
                        super::super::builtins::common::floor_div(
                            super::super::builtins::common::sub(
                                super::super::builtins::common::index(
                                    &(symbol_15.clone()),
                                    symbol_18,
                                )?
                                .clone(),
                                super::super::builtins::common::index(
                                    &(symbol_17.clone()),
                                    symbol_18,
                                )?
                                .clone(),
                            )?,
                            super::super::builtins::common::index(
                                &(attribute_0.clone()),
                                symbol_18,
                            )?
                            .clone(),
                        )?,
                        1_i128,
                    )?
                }),
            )
        })
        .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?;
    super::super::builtins::shape::dimensions(
        &((super::super::builtins::shape::integers(&super::super::builtins::common::range(
            symbol_2,
        )?))
        .into_iter()
        .map(|symbol_20| -> super::super::builtins::BuiltinResult<i128> {
            Ok((if (symbol_20 == attribute_11) {
                super::super::builtins::common::div(
                    super::super::builtins::common::index(&(symbol_0.clone()), attribute_5)?
                        .clone(),
                    symbol_11,
                )?
            } else {
                (if (symbol_20 == attribute_12) {
                    super::super::builtins::common::index(&(symbol_1.clone()), attribute_9)?.clone()
                } else {
                    super::super::builtins::common::sum(
                        &((symbol_4.clone())
                            .into_iter()
                            .map(|symbol_21| -> super::super::builtins::BuiltinResult<i128> {
                                Ok((if (super::super::builtins::common::index(
                                    &(symbol_7.clone()),
                                    symbol_21,
                                )?
                                .clone()
                                    == symbol_20)
                                {
                                    super::super::builtins::common::index(
                                        &(symbol_19.clone()),
                                        symbol_21,
                                    )?
                                    .clone()
                                } else {
                                    0_i128
                                }))
                            })
                            .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?),
                    )?
                })
            }))
        })
        .collect::<super::super::builtins::BuiltinResult<Vec<i128>>>()?),
    )
}
/// TEPL shape program for TensorLang.all_reduce.
fn shape_27(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::CollectiveReduce {
        channel_id: field_1,
        use_global_device_ids: field_2,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_1: i128 = i128::from(*field_1);
    let attribute_2: bool = field_2.clone();
    super::super::builtins::shape::dimensions(&(symbol_0.clone()))
}
/// TEPL shape program for TensorLang.all_to_all.
fn shape_29(
    operands: &[&[u64]],
    attrs: &OpAttrs,
) -> super::super::builtins::BuiltinResult<Vec<u64>> {
    let symbol_0: Vec<i128> = super::super::builtins::shape::integers(operands[0]);
    let OpAttrs::TensorLang(super::super::dialects::tensor_lang::OpAttrs::AllToAllAttrs {
        split_dimension: field_0,
        concat_dimension: field_1,
        split_count: field_2,
        channel_id: field_4,
        ..
    }) = attrs
    else {
        return Err(super::super::builtins::BuiltinError::Assertion(
            "invalid metadata attributes",
        ));
    };
    let attribute_0: i128 = i128::from(*field_0);
    let attribute_1: i128 = i128::from(*field_1);
    let attribute_2: i128 = i128::from(*field_2);
    let attribute_4: i128 = i128::from(*field_4);
    let symbol_1: i128 = attribute_0;
    let symbol_2: i128 = attribute_1;
    let symbol_3: i128 = attribute_2;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(Vec::<i128>::from([symbol_1])),
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        ),
        "TensorLang.all_to_all shape assertion at 401:13",
    )?;
    super::super::builtins::common::ensure(
        super::super::builtins::shape::is_valid_axis_list(
            &(Vec::<i128>::from([symbol_2])),
            (super::super::builtins::common::len(&(symbol_0.clone())) as i128),
        ),
        "TensorLang.all_to_all shape assertion at 402:13",
    )?;
    super::super::builtins::common::ensure(
        (symbol_3 > 0_i128),
        "TensorLang.all_to_all shape assertion at 403:13",
    )?;
    super::super::builtins::common::ensure(
        (super::super::builtins::common::rem(
            super::super::builtins::common::index(&(symbol_0.clone()), symbol_1)?.clone(),
            symbol_3,
        )? == 0_i128),
        "TensorLang.all_to_all shape assertion at 404:13",
    )?;
    let symbol_4: Vec<i128> = super::super::builtins::common::replace(
        &(symbol_0.clone()),
        symbol_1,
        super::super::builtins::common::div(
            super::super::builtins::common::index(&(symbol_0.clone()), symbol_1)?.clone(),
            symbol_3,
        )?,
    )?;
    super::super::builtins::shape::dimensions(
        &(super::super::builtins::common::replace(
            &(symbol_4.clone()),
            symbol_2,
            super::super::builtins::common::mul(
                super::super::builtins::common::index(&(symbol_4.clone()), symbol_2)?.clone(),
                symbol_3,
            )?,
        )?),
    )
}
